import React from 'react';
import {Audio} from '@remotion/media';
import {AbsoluteFill,Easing,Img,Sequence,interpolate,staticFile,useCurrentFrame,useVideoConfig} from 'remotion';

export type DailyStencilProps={mainArtwork:string;studioTransfer:string;collectionName:string;stencilTitle:string;date:string;suggestedPlacement:string;downloadUrl:string;caption?:string;audioFile?:string;showQrCode?:boolean;qrDataUrl?:string};
export const defaultDailyStencilProps:DailyStencilProps={mainArtwork:'stencils/main-stencil.png',studioTransfer:'stencils/studio-transfer.png',collectionName:'Divine Realism',stencilTitle:'Crown of Grace',date:'Friday, July 17, 2026',suggestedPlacement:'Upper back · Outer forearm · Calf',downloadUrl:'https://beyondimagination.co.technology/beyond-tattoo/stencil-of-day.php',caption:'Premium Biblical Realism stencil pack — printer-ready and studio-tested.',audioFile:'',showQrCode:true,qrDataUrl:''};
const ink='#111',paper='#f7f5f0',muted='#666';
const AtomMark=()=> <div style={{display:'flex',alignItems:'center',gap:14}}><div style={{fontSize:44}}>⚛</div><div><div style={{fontSize:22,letterSpacing:3,textTransform:'uppercase'}}>atomic bit</div><div style={{fontSize:12,letterSpacing:6,textTransform:'uppercase'}}>Beyond</div></div></div>;
const Header:React.FC<Pick<DailyStencilProps,'collectionName'|'stencilTitle'|'date'>>=({collectionName,stencilTitle,date})=>{const f=useCurrentFrame();return <div style={{position:'absolute',top:72,left:64,right:64,display:'flex',justifyContent:'space-between',opacity:interpolate(f,[0,35],[0,1],{extrapolateRight:'clamp'}),translate:`0 ${interpolate(f,[0,45],[24,0],{extrapolateRight:'clamp',easing:Easing.bezier(.16,1,.3,1)})}px`}}><AtomMark/><div style={{textAlign:'right'}}><div style={{fontSize:26,letterSpacing:6,textTransform:'uppercase'}}>{collectionName}</div><div style={{fontSize:60,fontFamily:'Georgia,serif',marginTop:8}}>{stencilTitle}</div><div style={{fontSize:22,color:muted,marginTop:8}}>{date}</div></div></div>};
const Card:React.FC<{src:string;label:string;start:number;end:number}>=({src,label,start,end})=>{const f=useCurrentFrame();return <div style={{position:'absolute',left:68,right:68,top:245,bottom:245,overflow:'hidden',borderRadius:34,background:'#fff',border:'1px solid #0002',boxShadow:'0 30px 80px #0003',opacity:interpolate(f,[start,start+30,end-25,end],[0,1,1,0],{extrapolateLeft:'clamp',extrapolateRight:'clamp'}),scale:interpolate(f,[start,end],[1.035,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'})}}><Img src={staticFile(src)} style={{width:'100%',height:'100%',objectFit:'contain',background:'#fff'}}/><div style={{position:'absolute',left:26,bottom:26,background:'#111e',color:'#fff',padding:'14px 22px',borderRadius:999,fontSize:20,letterSpacing:3,textTransform:'uppercase'}}>{label}</div></div>};
const End:React.FC<DailyStencilProps>=({collectionName,stencilTitle,suggestedPlacement,downloadUrl,caption,qrDataUrl})=>{const f=useCurrentFrame();const l=f-430;return <AbsoluteFill style={{padding:'220px 70px 90px',justifyContent:'center',alignItems:'center',opacity:interpolate(l,[0,30],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'})}}><div style={{width:'100%',background:'#fff',padding:50,borderRadius:36,textAlign:'center',border:'1px solid #0002',boxShadow:'0 30px 90px #0003',translate:`0 ${interpolate(l,[0,40],[36,0],{extrapolateLeft:'clamp',extrapolateRight:'clamp'})}px`}}><div style={{fontSize:24,letterSpacing:7,textTransform:'uppercase',color:muted}}>{collectionName}</div><div style={{fontSize:78,fontFamily:'Georgia,serif',marginTop:18,lineHeight:1.05}}>{stencilTitle}</div><div style={{fontSize:28,marginTop:34}}>Suggested placement</div><div style={{fontSize:38,fontWeight:800,marginTop:8}}>{suggestedPlacement}</div>{caption?<div style={{fontSize:25,lineHeight:1.45,color:muted,margin:'30px auto 0',maxWidth:760}}>{caption}</div>:null}<div style={{display:'flex',justifyContent:'center',alignItems:'center',gap:30,marginTop:42}}>{qrDataUrl?<Img src={qrDataUrl} style={{width:210,height:210}}/>:null}<div style={{textAlign:'left'}}><div style={{display:'inline-block',background:ink,color:'#fff',fontSize:30,fontWeight:900,padding:'22px 34px',borderRadius:16}}>DOWNLOAD THE PACK</div><div style={{fontSize:18,color:muted,marginTop:16,maxWidth:470,overflowWrap:'anywhere'}}>{downloadUrl}</div></div></div></div></AbsoluteFill>};
export const DailyStencilPack:React.FC<DailyStencilProps>=(p)=>{const f=useCurrentFrame();const {durationInFrames}=useVideoConfig();return <AbsoluteFill style={{fontFamily:'Arial,Helvetica,sans-serif',color:ink,background:paper}}><AbsoluteFill style={{opacity:.13,backgroundImage:'radial-gradient(#111 0.7px,transparent 0.7px)',backgroundSize:'12px 12px'}}/><Header collectionName={p.collectionName} stencilTitle={p.stencilTitle} date={p.date}/><Card src={p.mainArtwork} label="Main stencil artwork" start={35} end={255}/><Card src={p.studioTransfer} label="Studio transfer template" start={235} end={455}/><Sequence from={430}><End {...p}/></Sequence><div style={{position:'absolute',bottom:0,left:0,right:0,height:10,background:'#0002'}}><div style={{height:'100%',width:`${interpolate(f,[0,durationInFrames-1],[0,100])}%`,background:ink}}/></div>{p.audioFile?<Audio src={staticFile(p.audioFile)}/>:null}</AbsoluteFill>};
