<?php
declare(strict_types=1);
require_once __DIR__ . '/../includes/app-layout.php';
$wallet = beyond_nav_bootstrap('Beyond Games');
?>
<!doctype html>
<html lang="en">
<head>
  <script>(function(){try{var t=localStorage.getItem('beyond-theme');document.documentElement.dataset.theme=['dark','light','sunset'].includes(t)?t:'sunset';}catch(e){document.documentElement.dataset.theme='sunset';}})();</script>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
  <meta name="theme-color" content="#07172e">
  <title>French Quest | Beyond Games</title>
  <meta name="description" content="A dialogue adventure across the French-speaking world.">
  <link rel="stylesheet" href="<?=e(beyond_url('assets/css/bos-21.css'))?>">
  <style>
    :root{--fq-blue:#4d91ff;--fq-sky:#70d9ff;--fq-gold:#ffd36a;--fq-navy:#07172e;--fq-card:#0d2240;--fq-line:rgba(151,203,255,.2)}
    *{box-sizing:border-box}.fq-page{min-height:100vh;color:#f4f8ff;background:radial-gradient(circle at 50% -20%,#1f5797 0,transparent 37%),linear-gradient(180deg,#07172e,#050b18 72%)}.fq-main{width:min(1280px,calc(100% - 24px));margin:auto;padding:16px 0 50px}.fq-top{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:14px}.fq-back{color:#c8ddf5;text-decoration:none;font-weight:900}.fq-logo{font-weight:1000;letter-spacing:.12em;text-transform:uppercase}.fq-logo b{color:var(--fq-gold)}.fq-save{padding:8px 12px;border:1px solid var(--fq-line);border-radius:999px;color:#8faac8;font-size:.68rem;font-weight:900}
    .fq-shell{overflow:hidden;border:1px solid var(--fq-line);border-radius:28px;background:#09172b;box-shadow:0 30px 100px rgba(0,0,0,.42)}.fq-hud{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:12px 18px;border-bottom:1px solid var(--fq-line);background:rgba(8,23,44,.94)}.fq-location{display:flex;align-items:center;gap:11px}.fq-pin{display:grid;place-items:center;width:44px;height:44px;border-radius:13px;background:linear-gradient(145deg,#2d76d5,#123968);font-size:1.35rem}.fq-location small,.fq-stat small{display:block;color:#86a2bf;font-size:.56rem;font-weight:900;letter-spacing:.13em;text-transform:uppercase}.fq-location strong{display:block;margin-top:3px}.fq-stats{display:flex;gap:26px}.fq-stat strong{display:block;margin-top:2px;font-size:1.05rem}.fq-stat.hearts strong{color:#ff759c}.fq-stat.xp strong{color:var(--fq-gold)}
    .fq-game{display:grid;grid-template-columns:230px minmax(0,1fr)}.fq-map{padding:20px 15px;border-right:1px solid var(--fq-line);background:#071326}.fq-map h2{margin:0 7px 15px;color:#809ab8;font-size:.65rem;letter-spacing:.15em;text-transform:uppercase}.fq-city{position:relative;width:100%;display:flex;align-items:center;gap:11px;padding:13px 10px;border:0;border-radius:13px;background:transparent;color:#819ab5;text-align:left;font:inherit;cursor:pointer}.fq-city+ .fq-city:before{content:"";position:absolute;left:29px;bottom:calc(100% - 1px);width:2px;height:14px;background:#23405f}.fq-city span{display:grid;place-items:center;flex:0 0 38px;height:38px;border:1px solid #274666;border-radius:50%;background:#0a1d35}.fq-city b,.fq-city small{display:block}.fq-city small{margin-top:2px;font-size:.62rem}.fq-city.active{background:linear-gradient(90deg,rgba(70,143,240,.25),transparent);color:#fff}.fq-city.active span{border-color:var(--fq-sky);box-shadow:0 0 20px rgba(73,173,255,.3)}.fq-city.locked{opacity:.42;cursor:not-allowed}.fq-vocab{margin-top:25px;padding:14px;border:1px solid var(--fq-line);border-radius:14px;background:#0b1d34}.fq-vocab b{display:block;color:var(--fq-gold);font-size:1.5rem}.fq-vocab span{color:#8da7c3;font-size:.65rem}
    .fq-scene{position:relative;min-height:680px;display:flex;flex-direction:column;justify-content:flex-end;overflow:hidden;background:linear-gradient(180deg,rgba(5,14,29,.03),rgba(5,14,29,.3) 48%,#061225),linear-gradient(135deg,#387ab5,#143862 55%,#10223c)}.fq-scene:before{content:"";position:absolute;inset:0;background:radial-gradient(circle at 76% 14%,#ffd989 0 4%,rgba(255,218,145,.28) 4.2% 13%,transparent 26%),linear-gradient(155deg,transparent 0 44%,rgba(5,14,29,.35) 44.2% 46%,transparent 46.2%),repeating-linear-gradient(90deg,transparent 0 72px,rgba(6,21,40,.2) 74px);opacity:.8}.fq-skyline{position:absolute;inset:auto 0 0;height:66%;opacity:.92}.fq-building{position:absolute;bottom:0;border:2px solid rgba(181,218,246,.14);background:#102d4d;box-shadow:inset 0 0 40px rgba(0,0,0,.23)}.fq-building:after{content:"";position:absolute;inset:18px;background:repeating-linear-gradient(0deg,transparent 0 24px,rgba(255,213,105,.45) 26px 31px),repeating-linear-gradient(90deg,transparent 0 25px,rgba(255,213,105,.34) 27px 32px)}.fq-building:nth-child(1){left:-3%;width:24%;height:47%;transform:skewY(-3deg)}.fq-building:nth-child(2){left:18%;width:18%;height:65%;background:#173b60}.fq-building:nth-child(3){right:19%;width:25%;height:56%;background:#0c2947}.fq-building:nth-child(4){right:-4%;width:25%;height:72%;background:#163758}.fq-ground{position:absolute;left:0;right:0;bottom:0;height:27%;background:linear-gradient(180deg,#13273d,#081321)}.fq-npc{position:absolute;z-index:2;right:10%;bottom:205px;width:170px;text-align:center}.fq-person{position:relative;width:106px;height:180px;margin:auto}.fq-person .head{position:absolute;z-index:2;top:0;left:29px;width:54px;height:62px;border-radius:48% 48% 43% 43%;background:#ad7554;box-shadow:inset 8px 0 rgba(72,39,35,.16)}.fq-person .hair{position:absolute;z-index:3;top:-6px;left:24px;width:64px;height:35px;border-radius:50% 50% 35% 35%;background:#251d2a}.fq-person .body{position:absolute;bottom:0;left:6px;width:100px;height:130px;border-radius:38px 38px 13px 13px;background:linear-gradient(135deg,#e7536a,#9f2947);clip-path:polygon(24% 0,76% 0,100% 100%,0 100%)}.fq-npc>span{display:inline-block;margin-top:7px;padding:6px 9px;border-radius:999px;background:#061326;color:#b9d1ea;font-size:.64rem;font-weight:900}
    .fq-dialogue{position:relative;z-index:5;margin:0 22px 22px;padding:21px;border:1px solid rgba(166,215,255,.28);border-radius:20px;background:rgba(5,16,31,.93);box-shadow:0 18px 55px rgba(0,0,0,.4);backdrop-filter:blur(16px)}.fq-speaker{display:flex;justify-content:space-between;gap:12px;color:var(--fq-sky);font-size:.65rem;font-weight:1000;letter-spacing:.12em;text-transform:uppercase}.fq-sound{border:0;background:none;color:#a8c1da;font:inherit;cursor:pointer}.fq-line{margin:10px 0 5px;font-size:clamp(1.35rem,3vw,2.15rem);font-weight:850}.fq-translation{margin:0;color:#9fb4ca;font-size:.82rem}.fq-pronunciation{display:inline-block;margin-top:8px;padding:5px 8px;border-radius:7px;background:#102846;color:#78cfff;font-size:.68rem}.fq-choices{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin-top:17px}.fq-choice{position:relative;padding:13px 14px;border:1px solid #315173;border-radius:12px;background:#0d2340;color:#e7f3ff;text-align:left;font:inherit;font-weight:800;cursor:pointer;transition:.18s}.fq-choice:hover,.fq-choice:focus-visible{transform:translateY(-2px);border-color:var(--fq-sky);background:#123158}.fq-choice small{display:block;margin-top:4px;color:#84a4c4;font-size:.65rem;font-weight:600}.fq-choice.correct{border-color:#5de0a0;background:#123b35}.fq-choice.wrong{border-color:#ff668c;background:#3a1726}.fq-feedback{min-height:22px;margin-top:10px;color:#9fb6cc;font-size:.75rem;font-weight:800}.fq-feedback.good{color:#6ce3aa}.fq-feedback.bad{color:#ff809f}.fq-progress{position:absolute;z-index:4;left:22px;right:22px;top:22px;display:flex;gap:7px}.fq-progress i{height:5px;flex:1;border-radius:999px;background:rgba(255,255,255,.18)}.fq-progress i.done{background:var(--fq-gold)}
    .fq-modal{position:absolute;z-index:20;inset:0;display:grid;place-items:center;padding:20px;background:rgba(3,10,21,.86);backdrop-filter:blur(12px)}.fq-modal[hidden]{display:none}.fq-card{width:min(440px,100%);padding:30px;border:1px solid #396693;border-radius:23px;background:linear-gradient(145deg,#113158,#08172b);text-align:center;box-shadow:0 30px 90px #000}.fq-badge{display:grid;place-items:center;width:94px;height:94px;margin:auto;border:3px solid var(--fq-gold);border-radius:50%;background:#0d2340;font-size:2.7rem;box-shadow:0 0 35px rgba(255,211,106,.2)}.fq-card h2{margin:18px 0 7px;font-size:2rem}.fq-card p{color:#a5bbd2;line-height:1.55}.fq-rewards{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin:20px 0}.fq-rewards div{padding:13px;border:1px solid var(--fq-line);border-radius:11px}.fq-rewards b{display:block;color:var(--fq-gold);font-size:1.3rem}.fq-rewards small{color:#87a0bb;font-size:.58rem;text-transform:uppercase}.fq-action{width:100%;padding:14px;border:0;border-radius:12px;background:linear-gradient(135deg,#367de2,#5fcbe8);color:white;font:inherit;font-weight:1000;text-transform:uppercase;cursor:pointer}
    @media(max-width:800px){.fq-game{grid-template-columns:1fr}.fq-map{display:flex;gap:5px;overflow:auto;padding:8px;border-right:0;border-bottom:1px solid var(--fq-line)}.fq-map h2,.fq-vocab{display:none}.fq-city{min-width:150px}.fq-city+.fq-city:before{display:none}.fq-scene{min-height:650px}}@media(max-width:560px){.fq-main{width:100%;padding:0}.fq-top{padding:11px;margin:0}.fq-save{display:none}.fq-shell{border-radius:0;border-left:0;border-right:0}.fq-hud{padding:9px 11px}.fq-stats{gap:10px}.fq-stat:first-child{display:none}.fq-location strong{font-size:.78rem}.fq-scene{min-height:calc(100dvh - 185px)}.fq-dialogue{margin:0 9px 9px;padding:16px 13px}.fq-choices{grid-template-columns:1fr}.fq-npc{right:2%;bottom:310px;transform:scale(.8);transform-origin:bottom}.fq-progress{top:12px;left:12px;right:12px}.fq-line{font-size:1.28rem}.fq-choice{padding:11px}.fq-card{padding:24px 18px}}
  </style>
</head>
<body class="bos-page fq-page">
<main class="fq-main">
  <header class="fq-top"><a class="fq-back" href="/beyond-games/">← Beyond Games</a><div class="fq-logo">French <b>Quest</b></div><span class="fq-save">● Adventure saved locally</span></header>
  <section class="fq-shell">
    <div class="fq-hud">
      <div class="fq-location"><span class="fq-pin" id="locationIcon">🗼</span><div><small>Mission 01 · Arrival</small><strong id="locationName">Paris · Café Saint-Paul</strong></div></div>
      <div class="fq-stats"><div class="fq-stat"><small>Streak</small><strong id="streak">0 🔥</strong></div><div class="fq-stat hearts"><small>Hearts</small><strong id="hearts">♥ ♥ ♥</strong></div><div class="fq-stat xp"><small>Quest XP</small><strong id="xp">0 XP</strong></div></div>
    </div>
    <div class="fq-game">
      <aside class="fq-map"><h2>World route</h2>
        <button class="fq-city active" data-city="paris"><span>🗼</span><div><b>Paris</b><small>Arrival · 0/4</small></div></button>
        <button class="fq-city locked" data-city="montreal"><span>🍁</span><div><b>Montréal</b><small>Locked · 4 words</small></div></button>
        <button class="fq-city locked" data-city="haiti"><span>🌴</span><div><b>Port-au-Prince</b><small>Locked · 8 words</small></div></button>
        <div class="fq-vocab"><b id="wordCount">0 / 12</b><span>passport words collected</span></div>
      </aside>
      <section class="fq-scene">
        <div class="fq-progress" id="progress"><i></i><i></i><i></i><i></i></div>
        <div class="fq-skyline"><i class="fq-building"></i><i class="fq-building"></i><i class="fq-building"></i><i class="fq-building"></i><i class="fq-ground"></i></div>
        <div class="fq-npc"><div class="fq-person"><i class="hair"></i><i class="head"></i><i class="body"></i></div><span id="npcName">Amélie · Café owner</span></div>
        <div class="fq-dialogue">
          <div class="fq-speaker"><span id="speaker">Amélie says</span><button class="fq-sound" id="sound" type="button">🔊 Hear French</button></div>
          <p class="fq-line" id="line">Bonjour ! Bienvenue à Paris.</p><p class="fq-translation" id="translation">Hello! Welcome to Paris.</p><span class="fq-pronunciation" id="pronunciation">bohn-zhoor · bee-ehn-vuh-new ah pah-ree</span>
          <div class="fq-choices" id="choices"></div><div class="fq-feedback" id="feedback">Choose the best reply.</div>
        </div>
        <div class="fq-modal" id="complete" hidden><div class="fq-card"><div class="fq-badge">🗼</div><h2>Paris passport stamped!</h2><p>You handled your first café conversation and collected four useful phrases.</p><div class="fq-rewards"><div><b id="earnedXp">+0 XP</b><small>Quest reward</small></div><div><b id="finalWords">4 words</b><small>Collected</small></div></div><button class="fq-action" id="replay">Replay mission</button></div></div>
      </section>
    </div>
  </section>
</main>
<script>
(()=>{
  const missions=[
    {line:'Bonjour ! Bienvenue à Paris.',translation:'Hello! Welcome to Paris.',pron:'bohn-zhoor · bee-ehn-vuh-new ah pah-ree',word:'bonjour',choices:[['Bonjour !','Hello!'],['Bonne nuit.','Good night.'],['Au revoir.','Goodbye.']],answer:0,note:'Bonjour is the polite greeting used throughout the day.'},
    {line:'Vous désirez quelque chose ?',translation:'Would you like something?',pron:'voo day-zee-ray kel-kuh shohz',word:'je voudrais',choices:[['Je voudrais un café, s’il vous plaît.','I would like a coffee, please.'],['Je suis un café.','I am a coffee.'],['Où est le train ?','Where is the train?']],answer:0,note:'Je voudrais… is a polite, versatile way to order.'},
    {line:'Avec du lait ou du sucre ?',translation:'With milk or sugar?',pron:'ah-vek dew lay oo dew sew-kruh',word:'sans sucre',choices:[['Sans sucre, merci.','Without sugar, thank you.'],['Je ne parle pas café.','I do not speak coffee.'],['À demain, lait.','See you tomorrow, milk.']],answer:0,note:'Sans means “without.” Merci keeps the reply courteous.'},
    {line:'Voilà votre café. Bonne journée !',translation:'Here is your coffee. Have a good day!',pron:'vwah-lah vot-ruh kah-fay · bun zhoor-nay',word:'bonne journée',choices:[['Merci, bonne journée !','Thank you, have a good day!'],['Bonsoir hier.','Good evening yesterday.'],['Non, je suis Paris.','No, I am Paris.']],answer:0,note:'Bonne journée is a natural farewell during the daytime.'}
  ];
  const $=s=>document.querySelector(s);let step=0,hearts=3,xp=0,streak=0,answered=false,words=[];
  function speak(){if(!('speechSynthesis'in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(missions[step].line);u.lang='fr-FR';u.rate=.82;window.speechSynthesis.speak(u)}
  function render(){answered=false;const m=missions[step];$('#line').textContent=m.line;$('#translation').textContent=m.translation;$('#pronunciation').textContent=m.pron;$('#feedback').textContent='Choose the best reply.';$('#feedback').className='fq-feedback';$('#choices').innerHTML='';m.choices.forEach((c,i)=>{const b=document.createElement('button');b.className='fq-choice';b.innerHTML=c[0]+'<small>'+c[1]+'</small>';b.onclick=()=>choose(i,b);$('#choices').appendChild(b)});document.querySelectorAll('#progress i').forEach((x,i)=>x.classList.toggle('done',i<step));document.querySelector('.fq-city small').textContent='Arrival · '+step+'/4'}
  function choose(i,b){if(answered)return;answered=true;const m=missions[step],buttons=[...document.querySelectorAll('.fq-choice')];if(i===m.answer){b.classList.add('correct');streak++;xp+=10+streak*2;if(!words.includes(m.word))words.push(m.word);$('#feedback').textContent='✓ '+m.note;$('#feedback').className='fq-feedback good'}else{b.classList.add('wrong');buttons[m.answer].classList.add('correct');hearts=Math.max(0,hearts-1);streak=0;$('#feedback').textContent='Not quite. '+m.note;$('#feedback').className='fq-feedback bad'}update();setTimeout(()=>{if(step<missions.length-1){step++;render()}else finish()},1250)}
  function update(){$('#hearts').textContent='♥ '.repeat(hearts).trim()||'—';$('#xp').textContent=xp+' XP';$('#streak').textContent=streak+' 🔥';$('#wordCount').textContent=words.length+' / 12';document.querySelector('.fq-city small').textContent='Arrival · '+Math.min(step+(answered?1:0),4)+'/4'}
  function finish(){document.querySelectorAll('#progress i').forEach(x=>x.classList.add('done'));$('#earnedXp').textContent='+'+xp+' XP';$('#finalWords').textContent=words.length+' words';$('#complete').hidden=false;const saved=JSON.parse(localStorage.getItem('french-quest-save')||'{"xp":0,"words":[]}');saved.xp=Math.max(saved.xp||0,xp);saved.words=[...new Set([...(saved.words||[]),...words])];localStorage.setItem('french-quest-save',JSON.stringify(saved))}
  function reset(){step=0;hearts=3;xp=0;streak=0;words=[];$('#complete').hidden=true;update();render()}
  $('#sound').onclick=speak;$('#replay').onclick=reset;document.querySelectorAll('.fq-city').forEach(b=>b.onclick=()=>{if(b.classList.contains('locked')){$('#feedback').textContent='Complete Paris to unlock this destination.';$('#feedback').className='fq-feedback bad'}});
  update();render();
})();
</script>
<?php bos_page_end(); ?>
