<?php
// Run hourly from CLI. Web execution requires DAILY_STUDIO_CRON_TOKEN.
if (PHP_SAPI!=='cli') { $token=getenv('DAILY_STUDIO_CRON_TOKEN')?:''; if(!$token || !hash_equals($token,$_GET['token']??'')){http_response_code(403);exit('Forbidden');}}
$root=dirname(__DIR__,3);$dbPath=$root.'/var/daily-studio.sqlite';if(!file_exists($dbPath)){exit("Daily Studio database not initialized. Open the admin page first.\n");}
$db=new PDO('sqlite:'.$dbPath,null,null,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
$db->exec("UPDATE events SET status='scheduled' WHERE status='draft' AND requires_approval=0 AND scheduled_at<=datetime('now','+10 minutes')");
$q=$db->query("SELECT * FROM events WHERE status='scheduled' AND scheduled_at<=datetime('now','localtime') ORDER BY scheduled_at LIMIT 50");$events=$q->fetchAll();$outDir=$root.'/var/daily-studio-published';if(!is_dir($outDir))mkdir($outDir,0755,true);
foreach($events as $e){try{$db->beginTransaction();$lock=$db->prepare("UPDATE events SET status='publishing',attempts=attempts+1 WHERE id=? AND status='scheduled'");$lock->execute([$e['id']]);if(!$lock->rowCount()){$db->rollBack();continue;}$payload=['id'=>(int)$e['id'],'channel'=>$e['channel_key'],'title'=>$e['title'],'type'=>$e['content_type'],'scheduled_at'=>$e['scheduled_at'],'content'=>json_decode($e['content_json'],true),'published_at'=>date(DATE_ATOM)];file_put_contents($outDir.'/'.$e['channel_key'].'.json',json_encode($payload,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE),LOCK_EX);$db->prepare("UPDATE events SET status='published',published_at=CURRENT_TIMESTAMP,last_error=NULL WHERE id=?")->execute([$e['id']]);$db->prepare("INSERT INTO publish_logs(event_id,status,detail) VALUES(?,'published','Channel snapshot written')")->execute([$e['id']]);$db->commit();}catch(Throwable $x){if($db->inTransaction())$db->rollBack();$db->prepare("UPDATE events SET status='failed',last_error=? WHERE id=?")->execute([$x->getMessage(),$e['id']]);}}
echo count($events)." event(s) processed.\n";
