<?php
require_once __DIR__.'/../includes/app-layout.php';
$wallet=bos_page_start('Beyond OS','Dashboard','Your Live, Learn and Earn command center.');
$bits=number_format((float)($wallet['balance']??0));
?>
<main class="bos-main"><section class="bos-hero"><span class="bos-kicker">Beyond OS 2.1 Beta</span><h1>One life.<br>LIVE it.</h1><p>Your connected command center for health, education, entertainment, careers and earnings.</p><div class="bos-actions"><a class="bos-btn" href="<?=e(beyond_url('beyond-id/dashboard/'))?>">Manage Beyond ID</a><a class="bos-btn secondary" href="<?=e(beyond_url('beyond-finance/'))?>"><?=$bits?> BIT$</a></div></section>
<section class="bos-section"><h2>❤️ Live</h2><p>Daily experiences for your faith, health and entertainment.</p><div class="bos-grid"><?php echo bos_app_card('Daily Breath','Prayer, Scripture, plans and reflection.','dailybreath/','✝'); echo bos_app_card('Beyond Health','Track workouts, nutrition, weight and habits.','beyond-health/','♥'); echo bos_app_card('Beyond TV','Watch Beyond Originals and live channels.','beyond-tv/','▶'); ?></div></section>
<section class="bos-section"><h2>🎓 Learn</h2><p>From preschool through career-ready skills.</p><div class="bos-grid"><?php echo bos_app_card('Beyond Preschool','Early learning, stories, colors and numbers.','beyond-preschool/','🧸'); echo bos_app_card('Beyond Code / Math','Learn, build projects and prepare for work.','beyond-math/','Σ'); echo bos_app_card('Beyond French','Languages, conversation and global tours.','beyond-french/','FR'); echo bos_app_card('Beyond Space','Explore the universe.','beyond-space/','🚀'); echo bos_app_card('Beyond Ancient','Explore civilizations and history.','beyond-ancient/','🏺');  ?></div></section>
<section class="bos-section"><h2>💼 Earn</h2><p>Build a career, complete tasks and sell your work.</p><div class="bos-grid"><?php echo bos_app_card('Beyond Careers','Resume, portfolio, job readiness and tasks.','beyond-careers/','💼'); echo bos_app_card('Beyond Sell','Products, digital goods, auctions and services.','beyond-sell/','🛍'); echo bos_app_card('Beyond Finance','bit$, cash, budgets and transactions.','beyond-finance/','▣'); echo bos_app_card('Beyond Catering','Launch and manage a food business.','beyond-catering/','🍽'); echo bos_app_card('Beyond Tattoo','Design, discover, book and sell stencils.','beyond-tattoo/','✦'); ?></div></section></main>
<?php bos_page_end(); ?>
