<?php
require_once __DIR__.'/../includes/app-layout.php';
$wallet=bos_page_start('Beyond OS','Dashboard','Your Live, Learn and Earn command center.');
$bits=number_format((float)($wallet['balance']??0));
?>
<main class="bos-main"><section class="bos-hero"><span class="bos-kicker">Beyond OS 2.1 Beta</span><h1>One life.<br>LIVE it.</h1><p>Your connected command center for health, education, entertainment, careers and earnings.</p><div class="bos-actions"><a class="bos-btn" href="<?=e(beyond_url('beyond-id/dashboard/'))?>">Manage Beyond ID</a><a class="bos-btn secondary" href="<?=e(beyond_url('beyond-id/dashboard/wallet.php'))?>"><?=$bits?> BIT$</a></div></section>
<section class="bos-section"><h2>❤️ Live</h2><p>Daily experiences for your faith, health and entertainment.</p><div class="bos-grid"><?php echo bos_app_card('Daily Breath','Prayer, Scripture, plans and reflection.','dailybreath/','✝'); echo bos_app_card('Beyond Health','Wellness practices for mind, body and daily life.','dailybreath/practices.php','♥'); echo bos_app_card('Beyond TV','Watch Beyond Originals and live channels.','beyond-tv/','▶'); ?></div></section>
<section class="bos-section"><h2>🎓 Learn</h2><p>From preschool through career-ready skills.</p><div class="bos-grid"><?php echo bos_app_card('Beyond Preschool','Early learning, stories, colors and numbers.','beyond-preschool/','🧸'); echo bos_app_card('Beyond Math Academy','Interactive math lessons, tests and module exams.','beyond-math/academy.php','Σ'); echo bos_app_card('Beyond Coding School','Six career pathways for designers and developers.','coding-school/','⌘'); echo bos_app_card('Beyond French','Languages, conversation and global tours.','beyond-french/','FR'); echo bos_app_card('Beyond Space','Explore the universe.','beyond-space/','🚀'); echo bos_app_card('Beyond Ancient','Explore civilizations and history.','beyond-tv/channel.php?slug=beyond-ancient','🏺'); ?></div></section>
<section class="bos-section"><h2>💼 Earn</h2><p>Build a career, complete tasks and sell your work.</p><div class="bos-grid"><?php echo bos_app_card('Career Pathways','Build a portfolio and job-ready development skills.','coding-school/','💼'); echo bos_app_card('Beyond Marketplace','Discover creator products and selling experiences.','beyond-market/','▦'); echo bos_app_card('Beyond Sell','Products, digital goods, auctions and services.','beyond-sell/','🛍'); echo bos_app_card('Beyond Wallet','bit$, rewards and transactions.','beyond-id/dashboard/wallet.php','▣'); echo bos_app_card('Catering Enquiries','Talk to Beyond about launching a food business.','contact.php?topic=catering','🍽'); echo bos_app_card('Beyond Tattoo','Design, discover, book and sell stencils.','beyond-tattoo/','✦'); ?></div></section></main>
<?php bos_page_end(); ?>
