<?php
declare(strict_types=1);require __DIR__.'/includes/functions.php';
$age=french_valid_age_group((string)($_GET['age']??$_POST['age']??'kids'));$module=french_valid_module((string)($_GET['module']??$_POST['module']??'greetings'));$course=french_academy_modules()[$module];$progress=french_academy_module_progress($age,$module);
if(!$course||(!$progress['exam_passed']&&$progress['lessons_passed']<10&&!is_admin())){http_response_code(403);exit('Module exam is locked.');}$questions=french_module_exam_questions($age,$module);$result=null;
if($_SERVER['REQUEST_METHOD']==='POST'){if(!french_verify_csrf()){$result=['score'=>0,'passed'=>false];}else{$score=french_score_quiz($questions,(array)($_POST['answers']??[]));$passed=french_record_module_exam($age,$module,$score,count($questions));$result=['score'=>$score,'passed'=>$passed];}}
$pageTitle=$course['title'].' Exam | French Academy';require __DIR__.'/includes/header.php';
?>
<div class="academy-wrap"><a class="academy-back" href="course.php?age=<?=h($age)?>&module=<?=h($module)?>">← Return to module</a><header class="course-head"><div><span class="eyebrow">MODULE EXAM</span><h1><?=h($course['icon'].' '.$course['title'])?></h1><p>One question from each lesson. Score 8/10 to complete this course module.</p></div></header><?php if($result):?><section class="result-card<?=$result['passed']?' pass':''?>"><h2><?=$result['passed']?'Module completed!':'Review and try again'?></h2><p>Your score: <strong><?=$result['score']?>/10</strong>.</p><?php if($result['passed']):?><a class="academy-button" href="academy.php?age=<?=h($age)?>">Continue your learning path</a><?php endif;?></section><?php endif;?><form class="quiz-form" method="post"><input type="hidden" name="csrf_token" value="<?=h(french_csrf_token())?>"><input type="hidden" name="age" value="<?=h($age)?>"><input type="hidden" name="module" value="<?=h($module)?>"><?php foreach($questions as $index=>$question):?><fieldset class="quiz-question"><h3><?=($index+1)?>. <?=h($question['prompt'])?></h3><div class="quiz-options"><?php foreach($question['options'] as $option):?><label class="quiz-option"><input type="radio" name="answers[<?=$index?>]" value="<?=h($option)?>" required><span><?=h($option)?></span></label><?php endforeach;?></div></fieldset><?php endforeach;?><button class="academy-button" type="submit">Submit module exam</button></form></div>
<?php require __DIR__.'/includes/footer.php';?>
