<?php
declare(strict_types=1);require __DIR__.'/includes/functions.php';require_once __DIR__.'/../includes/ecosystem.php';
$age=french_valid_age_group((string)($_GET['age']??$_POST['age']??'kids'));$module=french_valid_module((string)($_GET['module']??$_POST['module']??'greetings'));$lessonNumber=max(1,min(10,(int)($_GET['lesson']??$_POST['lesson']??1)));$lesson=french_course_lesson($age,$module,$lessonNumber);
if(!$lesson||!french_academy_lesson_unlocked($age,$module,$lessonNumber)){http_response_code(403);exit('Lesson test is locked.');}$questions=french_lesson_test_questions($age,$module,$lessonNumber);$result=null;
if($_SERVER['REQUEST_METHOD']==='POST'){if(!french_verify_csrf()){$result=['score'=>0,'passed'=>false,'error'=>'Session expired.'];}else{$score=french_score_quiz($questions,(array)($_POST['answers']??[]));$passed=french_record_lesson_test($age,$module,$lessonNumber,$score,count($questions));$reward=$passed?beyond_award_reward((int)($_SESSION['user_id']??0),'beyond-french','lesson',$age.':'.$module.':'.$lessonNumber,10,'French Academy lesson completed — '.$lesson['title']):null;$result=['score'=>$score,'passed'=>$passed,'reward'=>$reward];}}
$pageTitle=$lesson['title'].' Test | French Academy';require __DIR__.'/includes/header.php';
?>
<div class="academy-wrap"><a class="academy-back" href="academy-lesson.php?age=<?=h($age)?>&module=<?=h($module)?>&lesson=<?=$lessonNumber?>">← Review lesson</a><header class="course-head"><div><span class="eyebrow">LESSON <?=$lessonNumber?> TEST</span><h1><?=h($lesson['title'])?></h1><p>Answer 10 questions. You need 8 correct answers to unlock the next lesson.</p></div></header><?php if($result):?><section class="result-card<?=$result['passed']?' pass':''?>"><h2><?=$result['passed']?'Passed — excellent work!':'Keep practicing'?></h2><p>Your score: <strong><?=$result['score']?>/10</strong>.</p><?php if($result['passed']):?><?php if($lessonNumber<10):?><a class="academy-button" href="academy-lesson.php?age=<?=h($age)?>&module=<?=h($module)?>&lesson=<?=$lessonNumber+1?>">Continue to Lesson <?=$lessonNumber+1?></a><?php else:?><a class="academy-button" href="academy-exam.php?age=<?=h($age)?>&module=<?=h($module)?>">Take module exam</a><?php endif;?><?php endif;?></section><?php endif;?><form class="quiz-form" method="post"><input type="hidden" name="csrf_token" value="<?=h(french_csrf_token())?>"><input type="hidden" name="age" value="<?=h($age)?>"><input type="hidden" name="module" value="<?=h($module)?>"><input type="hidden" name="lesson" value="<?=$lessonNumber?>"><?php foreach($questions as $index=>$question):?><fieldset class="quiz-question"><h3><?=($index+1)?>. <?=h($question['prompt'])?></h3><div class="quiz-options"><?php foreach($question['options'] as $option):?><label class="quiz-option"><input type="radio" name="answers[<?=$index?>]" value="<?=h($option)?>" required><span><?=h($option)?></span></label><?php endforeach;?></div></fieldset><?php endforeach;?><button class="academy-button" type="submit">Submit lesson test</button></form></div>
<?php require __DIR__.'/includes/footer.php';?>
