<?php
declare(strict_types=1);require __DIR__.'/includes/functions.php';
$age=french_valid_age_group((string)($_GET['age']??'kids'));$module=french_valid_module((string)($_GET['module']??'greetings'));$_SESSION['french_academy_age']=$age;
$course=french_academy_modules()[$module];$group=french_age_groups()[$age];$accessible=french_academy_module_accessible($module);$progress=french_academy_module_progress($age,$module);$pageTitle=$course['title'].' | French Academy';require __DIR__.'/includes/header.php';
?>
<div class="academy-wrap"><a class="academy-back" href="academy.php?age=<?=h($age)?>">← All modules</a>
<?php if(!$accessible):?><section class="locked-panel"><span class="module-icon">🔒</span><h1><?=h($course['title'])?></h1><p>This is a Full Academy module. The free <?=h($group['title'])?> course is Greetings.</p><a class="academy-button" href="course.php?age=<?=h($age)?>&module=greetings">Open free module</a></section>
<?php else:?><header class="course-head"><div><span class="eyebrow"><?=h($group['title'])?> · <?=h($group['ages'])?></span><h1><?=h($course['icon'].' '.$course['title'])?></h1><p><?=h($course['description'])?></p></div><span class="academy-badge <?=$progress['exam_passed']?'done':''?>"><?=$progress['lessons_passed']?>/10 lessons</span></header><div class="lesson-list">
<?php for($lesson=1;$lesson<=10;$lesson++):$item=french_course_lesson($age,$module,$lesson);$passed=french_academy_lesson_passed($age,$module,$lesson);$unlocked=french_academy_lesson_unlocked($age,$module,$lesson);?><article class="academy-lesson-row<?=$unlocked?'':' locked'?>"><span class="lesson-number"><?=$lesson?></span><div><h3><?=h($item['title'])?></h3><p><?=h($item['english'])?> · Lesson test required</p></div><?php if($unlocked):?><a class="academy-button <?=$passed?'secondary':''?>" href="academy-lesson.php?age=<?=h($age)?>&module=<?=h($module)?>&lesson=<?=$lesson?>"><?=$passed?'Review':'Start'?></a><?php else:?><span class="academy-badge locked">Locked</span><?php endif;?></article><?php endfor;?></div>
<?php $examUnlocked=$progress['lessons_passed']===10||is_admin();?><section class="exam-card"><span class="eyebrow" style="color:#aee6ff">MODULE EXAM</span><h2>10-question <?=h($course['title'])?> exam</h2><p>Pass all lesson tests to unlock the exam. A score of 8/10 is required.</p><a class="academy-button <?=$examUnlocked?'':'locked'?>" href="academy-exam.php?age=<?=h($age)?>&module=<?=h($module)?>"><?=$progress['exam_passed']?'Review exam':($examUnlocked?'Take exam':'Complete 10 lessons')?></a></section><?php endif;?></div>
<?php require __DIR__.'/includes/footer.php';?>
