<?php
require_once __DIR__ . '/../includes/ecosystem.php';
$isGuest = empty($_SESSION['user_id']);
if ($isGuest) {
    $beyondWallet = beyond_nav_bootstrap('Beyond French', ['balance'=>0,'currency'=>'BITS','status'=>'guest']);
} else {
    $beyondWallet = beyond_app_bootstrap('Beyond French');
}
$pageTitle = 'Free Dictionary & Bible | Beyond French';
require __DIR__ . '/includes/header.php';
$dictionary = json_decode((string)@file_get_contents(__DIR__ . '/data/dictionary.json'), true) ?: [];
?>
<style>
.dictionary-hero{padding:clamp(34px,7vw,76px) 0 28px}.dictionary-hero h1{max-width:860px;margin:10px 0 14px;font-size:clamp(42px,7vw,76px);line-height:.96;letter-spacing:-.055em}.dictionary-hero p{max-width:760px;font-size:18px;line-height:1.65}.free-pill{display:inline-flex;padding:8px 12px;border-radius:999px;background:#eaf2ff;color:#1768ff;font-size:12px;font-weight:900}.dictionary-shell{display:grid;grid-template-columns:minmax(0,1fr) 300px;gap:22px;align-items:start}.dictionary-panel,.bible-panel{padding:clamp(18px,4vw,30px);border:1px solid #dbe3f1;border-radius:26px;background:#fff;box-shadow:0 22px 70px #1b2e5612}.search-row{display:grid;grid-template-columns:1fr 180px;gap:10px}.search-row input,.search-row select{width:100%;padding:15px 16px;border:1px solid #cad5e6;border-radius:15px;background:#f8faff;font:inherit}.dictionary-meta{display:flex;justify-content:space-between;gap:12px;margin:16px 0;color:#63708a;font-size:13px}.dictionary-results{display:grid;gap:10px}.word-card{padding:17px;border:1px solid #e1e7f0;border-radius:18px;background:#fbfcff}.word-top{display:flex;justify-content:space-between;gap:12px}.word-top h3{margin:0;font-size:21px}.word-type{color:#1768ff;font-size:11px;font-weight:900;text-transform:uppercase}.translations{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px;margin-top:13px}.translation-line{padding:10px 11px;border-radius:12px;background:#f1f5fb}.translation-line small,.translation-line strong,.translation-line em{display:block}.translation-line small{color:#65728a;font-size:10px;font-weight:900;text-transform:uppercase}.translation-line em{color:#71809a;font-size:12px}.empty-state{padding:25px;text-align:center;color:#69758a;border:1px dashed #cbd5e5;border-radius:17px}.bible-panel{position:sticky;top:90px;background:linear-gradient(145deg,#09291c,#174b34);color:#fff}.bible-panel h2{font-size:30px;margin:10px 0}.bible-panel p{color:#dce9df;line-height:1.6}.bible-panel a{display:flex;justify-content:center;margin-top:18px;padding:14px 16px;border-radius:14px;color:#173f2c;background:#f1cf7d;text-decoration:none;font-weight:900}.guest-note{margin-top:14px;padding:13px;border-radius:14px;background:#ffffff12;color:#dce9df;font-size:12px}.guest-note a{display:inline;padding:0;color:#f1cf7d;background:none}.quick-tags{display:flex;gap:8px;overflow:auto;padding:12px 0 4px}.quick-tags button{white-space:nowrap;padding:9px 12px;border:1px solid #d8e1ef;border-radius:999px;background:#fff;color:#34415b;font-weight:800;cursor:pointer}@media(max-width:820px){.dictionary-shell{grid-template-columns:1fr}.bible-panel{position:relative;top:auto}.search-row{grid-template-columns:1fr}.translations{grid-template-columns:1fr}}
</style>
<section class="section dictionary-hero"><span class="free-pill">FREE · NO BEYOND ID REQUIRED</span><span class="eyebrow">WRITTEN TRANSLATION LIBRARY</span><h1>Dictionary and Bible, open to everyone.</h1><p>Search practical English and French words with written guides in Spanish, Haitian Kreyòl and Jamaican Patois. Open the complete public Bible beside your language study.</p></section>
<section class="section dictionary-shell">
<div class="dictionary-panel">
<div class="search-row"><input id="dictionary-search" type="search" placeholder="Search hello, merci, prayer, water…" autocomplete="off"><select id="language-filter" aria-label="Search language"><option value="all">All languages</option><option value="english">English</option><option value="french">French</option><option value="spanish">Spanish</option><option value="kreyol">Kreyòl</option><option value="patois">Patois</option></select></div>
<div class="quick-tags"><button data-query="greeting">Greetings</button><button data-query="conversation">Conversation</button><button data-query="travel">Travel</button><button data-query="faith">Faith</button><button data-query="encouragement">Encouragement</button><button data-query="">All</button></div>
<div class="dictionary-meta"><strong id="result-count"></strong><span>Written guides · tap French to hear it</span></div>
<div class="dictionary-results" id="dictionary-results"></div>
</div>
<aside class="bible-panel"><span class="eyebrow" style="color:#f1cf7d">SEARCHABLE READING COMPANION</span><h2>Beyond Bible</h2><p>Browse all 66 books, choose any chapter, search within the page, and use chapter narration. Reading is free outside Beyond ID.</p><a href="../dailybreath/bible.php?preview=1">Open the free Bible →</a><?php if($isGuest):?><div class="guest-note">No sign-in required. A <a href="../beyond-id/auth/register.php?app=beyond-french">Beyond ID</a> is only needed to save favourites, history and Academy progress.</div><?php endif;?></aside>
</section>
<script>
const words=<?= json_encode($dictionary, JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) ?>;
const input=document.getElementById('dictionary-search'),language=document.getElementById('language-filter'),results=document.getElementById('dictionary-results'),count=document.getElementById('result-count');
const esc=(value)=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function speak(text){if(!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='fr-FR';u.rate=.86;speechSynthesis.speak(u)}
function render(){const q=input.value.trim().toLocaleLowerCase();const lang=language.value;const filtered=words.filter(w=>{const fields=lang==='all'?[w.english,w.french,w.spanish,w.kreyol,w.patois,w.type]:[w[lang],w.type];return fields.some(v=>String(v||'').toLocaleLowerCase().includes(q))});count.textContent=`${filtered.length} ${filtered.length===1?'result':'results'}`;results.innerHTML=filtered.length?filtered.map(w=>`<article class="word-card"><div class="word-top"><h3>${esc(w.english)}</h3><span class="word-type">${esc(w.type)}</span></div><div class="translations"><button class="translation-line" type="button" data-speak="${esc(w.french)}" style="text-align:left;border:0;cursor:pointer"><small>🇫🇷 Français · 🔊</small><strong>${esc(w.french)}</strong><em>${esc(w.pronunciation)}</em></button><div class="translation-line"><small>🇪🇸 Español</small><strong>${esc(w.spanish)}</strong></div><div class="translation-line"><small>🇭🇹 Kreyòl</small><strong>${esc(w.kreyol)}</strong></div><div class="translation-line"><small>🇯🇲 Patois</small><strong>${esc(w.patois)}</strong></div></div></article>`).join(''):'<div class="empty-state"><strong>No written translation found.</strong><br>Try a shorter word or search all languages.</div>';results.querySelectorAll('[data-speak]').forEach(b=>b.onclick=()=>speak(b.dataset.speak))}
input.addEventListener('input',render);language.addEventListener('change',render);document.querySelectorAll('[data-query]').forEach(b=>b.onclick=()=>{input.value=b.dataset.query;render()});render();
</script>
<?php require __DIR__ . '/includes/footer.php'; ?>
