<?php
declare(strict_types=1);
require_once dirname(__DIR__,2).'/config/bootstrap.php';
function academy_stripe_secret(): string{return trim((string)beyond_config('stripe.secret_key',getenv('STRIPE_SECRET_KEY')?:''));}
function academy_stripe_webhook_secret(): string{return trim((string)beyond_config('stripe.academy_webhook_secret',getenv('STRIPE_ACADEMY_WEBHOOK_SECRET')?:''));}
function academy_stripe_price(): string{return trim((string)beyond_config('stripe.academy_price_id',getenv('STRIPE_ACADEMY_PRICE_ID')?:''));}
function academy_stripe_request(string $method,string $path,array $data=[]): array{
  $secret=academy_stripe_secret();if($secret==='')throw new RuntimeException('Stripe secret key is not configured.');if(!function_exists('curl_init'))throw new RuntimeException('The PHP cURL extension is required.');
  $curl=curl_init('https://api.stripe.com/v1/'.ltrim($path,'/'));$options=[CURLOPT_RETURNTRANSFER=>true,CURLOPT_TIMEOUT=>30,CURLOPT_CUSTOMREQUEST=>$method,CURLOPT_HTTPHEADER=>['Authorization: Bearer '.$secret]];if($data)$options[CURLOPT_POSTFIELDS]=http_build_query($data);curl_setopt_array($curl,$options);$body=curl_exec($curl);$status=(int)curl_getinfo($curl,CURLINFO_HTTP_CODE);$error=curl_error($curl);curl_close($curl);if($body===false)throw new RuntimeException('Stripe request failed: '.$error);$json=json_decode((string)$body,true);if($status<200||$status>=300)throw new RuntimeException((string)($json['error']['message']??'Stripe request failed.'));return is_array($json)?$json:[];
}
function academy_absolute_url(string $path): string{$https=!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off';return ($https?'https':'http').'://'.($_SERVER['HTTP_HOST']??'localhost').'/'.ltrim($path,'/');}
function academy_verify_stripe_signature(string $payload,string $header,string $secret,int $tolerance=300): bool{$parts=[];foreach(explode(',',$header) as $part){[$key,$value]=array_pad(explode('=',trim($part),2),2,'');$parts[$key][]=$value;}$timestamp=(int)($parts['t'][0]??0);if(!$timestamp||abs(time()-$timestamp)>$tolerance)return false;$expected=hash_hmac('sha256',$timestamp.'.'.$payload,$secret);foreach($parts['v1']??[] as $signature)if(hash_equals($expected,$signature))return true;return false;}
function academy_upsert_subscription(PDO $pdo,int $userId,string $customer,string $subscription,string $status,?string $start,?string $end): void{$values=[$userId,'stripe',$customer,$subscription,$status,$start,$end];$driver=$pdo->getAttribute(PDO::ATTR_DRIVER_NAME);if($driver==='sqlite')$pdo->prepare('INSERT INTO academy_subscriptions(user_id,provider,provider_customer_id,provider_subscription_id,status,current_period_start,current_period_end) VALUES(?,?,?,?,?,?,?) ON CONFLICT(user_id) DO UPDATE SET provider=excluded.provider,provider_customer_id=excluded.provider_customer_id,provider_subscription_id=excluded.provider_subscription_id,status=excluded.status,current_period_start=excluded.current_period_start,current_period_end=excluded.current_period_end,updated_at=CURRENT_TIMESTAMP')->execute($values);else $pdo->prepare('INSERT INTO academy_subscriptions(user_id,provider,provider_customer_id,provider_subscription_id,status,current_period_start,current_period_end) VALUES(?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE provider=VALUES(provider),provider_customer_id=VALUES(provider_customer_id),provider_subscription_id=VALUES(provider_subscription_id),status=VALUES(status),current_period_start=VALUES(current_period_start),current_period_end=VALUES(current_period_end),updated_at=CURRENT_TIMESTAMP')->execute($values);}
