<?php
declare(strict_types=1);
require_once __DIR__ . '/../includes/app-layout.php';
$wallet = bos_page_start('Beyond Market', 'Marketplace Listing', 'View a Beyond Market product.');
$id = max(0, (int) ($_GET['id'] ?? 0));
$listing = null;
try {
    $statement = beyond_db()->prepare("SELECT id,title,short_description,description,item_type,listing_type,price_cash,price_bits,currency,status,published_at FROM listings WHERE id=? AND status IN ('active','sold') LIMIT 1");
    $statement->execute([$id]);
    $listing = $statement->fetch() ?: null;
} catch (Throwable $exception) {
    $listing = null;
}
$isFree = $listing && (float) ($listing['price_cash'] ?? 0) <= 0 && (int) ($listing['price_bits'] ?? 0) <= 0;
?>
<main class="bos-main listing-main">
<?php if (!$listing): ?>
  <section class="bos-hero listing-missing"><span class="bos-kicker">Beyond Market</span><h1>Listing unavailable.</h1><p>This item may have ended, moved or not yet been published.</p><div class="bos-actions"><a class="bos-btn" href="<?=e(beyond_url('beyond-market/'))?>">Return to the market</a></div></section>
<?php else: ?>
  <?php if (!empty($_GET['created'])): ?><div class="created-notice">✓ Your listing is live in Beyond Market.</div><?php endif; ?>
  <nav class="listing-breadcrumb"><a href="<?=e(beyond_url('beyond-market/'))?>">Beyond Market</a><span>›</span><a href="<?=e(beyond_url('beyond-market/#live-listings'))?>">Live listings</a><span>›</span><b><?=e((string)$listing['title'])?></b></nav>
  <section class="listing-layout"><div class="listing-gallery"><div class="listing-art"><span><?=$listing['item_type']==='digital'?'▥':($listing['item_type']==='physical'?'□':'✦')?></span><small>BEYOND CREATOR MARKET</small></div><p>Product preview</p></div><div class="listing-details"><span class="bos-kicker"><?=e(ucfirst((string)$listing['listing_type']))?> · <?=e(ucfirst((string)$listing['item_type']))?></span><h1><?=e((string)$listing['title'])?></h1><p class="listing-description"><?=nl2br(e((string)($listing['description'] ?: $listing['short_description'])))?></p><div class="listing-price"><?php if($isFree):?><strong>Free</strong><span>Digital community download</span><?php else:?><strong><?php if((int)($listing['price_bits']??0)>0):?><?=number_format((int)$listing['price_bits'])?> bit$<?php endif;?><?php if((float)($listing['price_cash']??0)>0):?><?=((int)($listing['price_bits']??0)>0?' or ':'')?>$<?=number_format((float)$listing['price_cash'],2)?> <?=e((string)$listing['currency'])?><?php endif;?></strong><span>Secure Beyond Market checkout</span><?php endif;?></div><div class="listing-actions"><?php if($isFree):?><a class="bos-btn" href="checkout.php?id=<?=$id?>&amp;method=free">Get free download</a><?php else:?><?php if((int)($listing['price_bits']??0)>0):?><a class="bos-btn" href="checkout.php?id=<?=$id?>&amp;method=bits">Buy with bit$</a><?php endif;?><?php if((float)($listing['price_cash']??0)>0):?><a class="bos-btn secondary" href="checkout.php?id=<?=$id?>&amp;method=stripe">Pay with Stripe</a><?php endif;?><?php endif;?><button class="watch-listing" id="watchListing" type="button">♡ Add to watchlist</button></div><div class="buyer-points"><span>✓ Original creator listing</span><span>✓ Wallet-connected checkout</span><span>✓ Digital delivery tracking</span></div><p class="listing-id">Listing #<?=number_format($id)?> · Published <?=e((string)($listing['published_at']??'recently'))?></p></div></section>
<?php endif; ?>
</main>
<style>
.listing-main{width:min(1180px,calc(100% - 28px));padding-bottom:60px}.created-notice{margin:16px 0;padding:14px 17px;border:1px solid rgba(73,229,157,.35);border-radius:14px;background:rgba(41,195,127,.1);color:#74edbb;font-weight:900}.listing-breadcrumb{display:flex;gap:9px;align-items:center;overflow:auto;padding:17px 4px;color:#8f96b3;font-size:.82rem;white-space:nowrap}.listing-breadcrumb a{color:#d6d9e8;text-decoration:none}.listing-layout{display:grid;grid-template-columns:minmax(0,1fr) minmax(340px,.82fr);gap:18px}.listing-gallery,.listing-details{padding:clamp(22px,4vw,38px);border:1px solid var(--bos-line);border-radius:27px;background:rgba(15,16,42,.86)}.listing-art{display:grid;place-items:center;align-content:center;min-height:520px;border-radius:19px;background:radial-gradient(circle at 50% 42%,rgba(91,136,255,.6),transparent 31%),radial-gradient(circle at 75% 20%,rgba(239,73,158,.38),transparent 25%),linear-gradient(145deg,#161a49,#321c58 53%,#13152f);box-shadow:inset 0 0 70px rgba(255,255,255,.04)}.listing-art>span{font-size:9rem;filter:drop-shadow(0 18px 35px rgba(0,0,0,.35))}.listing-art>small{margin-top:14px;letter-spacing:.22em;color:#dde0f1;font-weight:950}.listing-gallery>p{margin-bottom:0;color:#838ba9;text-align:center;font-size:.76rem}.listing-details h1{font-size:clamp(2.6rem,6vw,4.7rem);line-height:.95;letter-spacing:-.055em}.listing-description{color:#b5bbd1;line-height:1.7}.listing-price{margin:24px 0;padding:20px;border:1px solid rgba(255,255,255,.1);border-radius:16px;background:#090c24}.listing-price strong,.listing-price span{display:block}.listing-price strong{font-size:2rem}.listing-price span{margin-top:4px;color:#8f97b4;font-size:.8rem}.listing-actions{display:grid;gap:9px}.listing-actions .bos-btn{justify-content:center}.watch-listing{padding:12px;border:1px solid var(--bos-line);border-radius:999px;background:transparent;color:white;font:inherit;font-weight:900;cursor:pointer}.watch-listing.saved{border-color:#ef64aa;color:#ff83bd}.buyer-points{display:grid;gap:8px;margin:22px 0;color:#aeb5cd;font-size:.82rem}.listing-id{color:#747d9d;font-size:.72rem}.listing-missing{background:linear-gradient(135deg,#171a3d,#40204f)}
@media(max-width:850px){.listing-layout{grid-template-columns:1fr}.listing-art{min-height:360px}}@media(max-width:560px){.listing-main{width:min(100% - 18px,1180px)}.listing-gallery,.listing-details{padding:18px 14px}.listing-art{min-height:300px}}
</style>
<script>document.getElementById('watchListing')?.addEventListener('click',event=>{const button=event.currentTarget;button.classList.toggle('saved');button.textContent=button.classList.contains('saved')?'♥ Watching':'♡ Add to watchlist'});</script>
<?php bos_page_end(); ?>
