<?php
declare(strict_types=1);
require __DIR__ . '/includes/config.php'; require_login();
$current=bt_current_user();if(!$current||empty($current['onboarding_complete']))redirect('onboarding.php');
$role=(string)$current['account_type'];$tattoos=$role==='client'?bt_list_tattoos(bt_current_user_id()):[];$artists=bt_list_artists();$jobs=$role==='artist'?bt_list_open_jobs():[];$metrics=$role==='owner'?bt_owner_metrics(bt_current_user_id()):[];
$pageTitle='Dashboard — Beyond Tattoo';require __DIR__.'/includes/header.php';$success=flash('success');$error=flash('error');
?>
<div class="app-shell"><header class="app-header"><div class="container app-header-inner"><a class="brand" href="dashboard.php"><img class="brand-icon" src="../assets/icons/beyond-tattoo-192.webp" alt=""><span>BEYOND <b>TATTOO</b></span></a><span class="role-badge"><?=e($role==='client'?'Canvas':ucfirst($role))?></span></div></header><main class="container dashboard"><?php if($success):?><div class="notice"><?=e($success)?></div><?php endif;?><?php if($error):?><div class="notice error-notice"><?=e($error)?></div><?php endif;?><div class="welcome-row"><div><span class="eyebrow"><?=$role==='owner'?'🏪 Studio workspace':($role==='artist'?'🎨 Artist workspace':'🖼️ Canvas workspace')?></span><h1 class="section-title">Welcome, <?=e($current['name']?:'Beyond member')?>.</h1><p class="section-copy"><?=$role==='owner'?'Manage real opportunities and connect with listed artists.':($role==='artist'?'Keep your profile current and review live studio opportunities.':'Plan tattoos, discover real artists, and keep a private healing journal.')?></p></div></div>
<?php if($role==='owner'):?>
<div class="metric-grid"><div class="panel"><small>Open roles</small><strong><?=(int)$metrics['open_jobs']?></strong></div><div class="panel"><small>Invitations saved</small><strong><?=(int)$metrics['invites']?></strong></div><div class="panel"><small>Listed artists</small><strong><?=(int)$metrics['listed_artists']?></strong></div></div><section class="panel action-panel"><div><h2>Build your artist roster</h2><p class="meta">Post an opportunity or contact artists through their current portfolio.</p></div><a class="btn btn-primary" href="hire-artists.php">Hire artists →</a></section>
<?php elseif($role==='artist'):?>
<div class="dashboard-grid"><section class="panel"><h2>Open opportunities</h2><div class="plan"><?php foreach($jobs as $job):?><div class="task"><span><strong><?=e($job['title'])?></strong><br><small class="meta"><?=e($job['studio_name'])?> • <?=e($job['opportunity_type'])?></small></span></div><?php endforeach;?><?php if(!$jobs):?><p class="meta">No studio opportunities have been posted yet.</p><?php endif;?></div></section><aside class="panel"><h2>Your Tattoo profile</h2><p><?=e($current['styles']?:'Add your styles so studios know what you do.')?></p><p class="meta"><?=e($current['city'])?><?= $current['availability']?' • '.e($current['availability']):''?></p><a class="btn btn-primary" href="onboarding.php">Edit profile</a><a class="btn btn-secondary" style="margin-top:10px" href="stencil-editor.php">Open stencil editor</a></aside></div>
<?php else:?>
<div class="dashboard-grid"><section class="panel"><h2>Your tattoo journey</h2><div class="tattoo-grid"><?php foreach(array_slice($tattoos,0,2) as $tattoo):?><article class="tattoo-mini"><span class="status"><?=$tattoo['status']==='active'?'● Active healing':'✓ Healed'?></span><h3><?=e($tattoo['name'])?></h3><p class="meta">Day <?=(int)$tattoo['healing_day']?> of <?=(int)$tattoo['healing_days']?></p><div class="progress"><span style="width:<?=(int)$tattoo['progress']?>%"></span></div></article><?php endforeach;?><?php if(!$tattoos):?><article class="tattoo-mini"><span class="status">Start here</span><h3>Add your first tattoo</h3><p class="meta">Track healing from the day of your appointment.</p><a class="btn btn-primary" href="add-tattoo.php">Add tattoo</a></article><?php endif;?></div></section><aside class="panel"><h2>Ottawa artists</h2><div class="plan"><?php foreach(array_slice($artists,0,3) as $artist):?><a class="task" href="artist-profile.php?slug=<?=urlencode($artist['slug'])?>"><span><strong><?=e($artist['display_name'])?></strong><br><small class="meta"><?=e($artist['styles'])?></small></span><strong>›</strong></a><?php endforeach;?></div><a class="btn btn-secondary btn-block" href="studios.php">Explore studios</a></aside></div>
<?php endif;?></main><nav class="bottom-nav"><a class="active" href="dashboard.php"><span>⌂</span>Home</a><?php if($role==='owner'):?><a href="hire-artists.php"><span>🤝</span>Hire</a><?php elseif($role==='artist'):?><a href="onboarding.php"><span>🖼️</span>Profile</a><?php else:?><a href="my-tattoos.php"><span>🎨</span>Tattoos</a><?php endif;?><a href="studios.php"><span>📍</span>Discover</a><a href="stencil-editor.php"><span>🖼️</span>Canvas</a><a href="profile.php"><span>👤</span>Account</a></nav></div>
<?php require __DIR__.'/includes/footer.php'; ?>

