<?php
declare(strict_types=1);
require_once __DIR__ . '/../includes/ecosystem.php';
require_once __DIR__ . '/includes/stencil-content.php';
$stencil = bt_stencil_content();
$signedIn = !empty($_SESSION['user_id']);
$_SESSION['stencil_csrf'] ??= bin2hex(random_bytes(24));
beyond_nav_bootstrap('Beyond Tattoo', beyond_wallet());
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=htmlspecialchars($stencil['title'])?> — Free Stencil of the Day | Beyond Tattoo</title>
<style>
:root{--bg:#09050d;--panel:rgba(34,15,42,.74);--line:#7f2b96;--pink:#e958d7;--violet:#8b5cf6;--text:#fff;--muted:#c9b9cf;--green:#42e67a}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 80% 0,#45155d 0,transparent 35%),linear-gradient(#0a0610,#060409);color:var(--text);font:16px/1.5 system-ui,sans-serif}.wrap{max-width:1120px;margin:auto;padding:28px 18px 90px}.hero{display:grid;grid-template-columns:1.05fr .95fr;gap:24px;align-items:center}.eyebrow{color:#f0a7ff;font-weight:800;text-transform:uppercase;letter-spacing:.14em}.hero h1{font-size:clamp(42px,8vw,82px);line-height:.95;margin:12px 0}.hero h2{margin:0 0 8px;color:#fff;font-size:clamp(24px,4vw,38px)}.hero p{color:var(--muted);font-size:18px;max-width:650px}.card{background:var(--panel);border:1px solid rgba(233,88,215,.35);border-radius:28px;box-shadow:0 24px 70px #0008;backdrop-filter:blur(18px)}.preview{padding:18px;position:relative}.preview img.stencil{display:block;width:100%;background:white;border-radius:20px}.date-badge{position:absolute;right:34px;top:34px;background:#0c0810e8;border:1px solid #ffffff2a;border-radius:16px;padding:10px 14px;text-align:right;font-weight:900;box-shadow:0 12px 30px #0009}.date-badge span{display:block;color:#bd66ff}.actions{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px;margin-top:24px}.asset-pack{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-top:24px}.asset-card{padding:18px}.asset-card h3{margin:10px 0 5px}.asset-card p{margin:0 0 15px;color:var(--muted);font-size:14px}.asset-tag{font-size:11px;font-weight:900;letter-spacing:.08em;color:#e6b3ff;text-transform:uppercase}.btn{appearance:none;border:0;border-radius:999px;padding:14px 20px;font-weight:850;text-decoration:none;cursor:pointer;display:inline-flex;align-items:center;justify-content:center;gap:8px}.primary{color:#fff;background:linear-gradient(100deg,var(--violet),#ed3ca4)}.secondary{color:#fff;background:#ffffff12;border:1px solid #ffffff28}.reward{margin-top:18px;padding:16px 18px;color:#ffe49a}.reward strong{color:var(--green)}.features{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-top:28px}.feature{padding:22px}.feature h3{margin:4px 0}.feature p{color:var(--muted);margin:0}.link-box{margin-top:18px;padding:14px 16px;word-break:break-word}.link-box a{color:#fff;font-weight:800}.promo{margin-top:28px;padding:14px}.promo img{display:block;width:100%;border-radius:20px}.legal{color:#9f8ea9;font-size:13px;margin-top:18px}@media(max-width:780px){.hero{grid-template-columns:1fr}.hero h1{font-size:52px}.features,.asset-pack{grid-template-columns:1fr}.actions{grid-template-columns:1fr}.date-badge{right:28px;top:28px;font-size:13px}}
</style></head><body><main class="wrap"><section class="hero"><div><div class="eyebrow">Beyond Tattoo · <?=htmlspecialchars($stencil['display_date'])?></div><h1>Stencil of the Day</h1><h2><?=htmlspecialchars($stencil['title'])?></h2><p><strong>Free for everyone.</strong> No Beyond ID is required to view, edit, print, or download today’s generated stencil. Signed-in members also receive <strong>+<?=intval($stencil['reward_bits'])?> bit$ once per day</strong> when they download.</p><div class="actions"><a id="downloadBtn" class="btn primary" href="api/stencil-download.php?type=png">↓ Studio transfer PNG</a><a class="btn secondary" href="stencil-editor.php">✦ Open advanced editor</a></div>
<div class="asset-pack" aria-label="Four optimized stencil assets">
<article class="card asset-card"><span class="asset-tag">1 · Artist preview</span><h3>Client-ready preview</h3><p>Full composition for consultations, social sharing, and placement review.</p><a class="btn secondary" href="api/stencil-download.php?type=preview">Download WebP</a></article>
<article class="card asset-card"><span class="asset-tag">2 · Studio transfer</span><h3>Printer-optimized</h3><p>Cleaner linework, open negative space, and ready-to-print Letter PDF or high-resolution PNG.</p><a class="btn primary" href="api/stencil-download.php?type=png">Download PNG</a><a class="btn secondary" style="margin-top:8px" href="api/stencil-download.php?type=package">Download full pack</a></article>
<article class="card asset-card"><span class="asset-tag">3 · Editable master</span><h3>Customize in editor</h3><p>Mirror, scale, rotate, adjust line weight, add text and export your final layout.</p><a class="btn secondary" href="api/stencil-download.php?type=editable">Download SVG</a></article>
<article class="card asset-card"><span class="asset-tag">4 · Placement guide</span><h3>Suggested body placement</h3><p>Studio reference with recommended sizing for outer forearm, upper arm, calf, and upper back placement.</p><a class="btn secondary" href="api/stencil-download.php?type=placement">Download Guide PDF</a></article>
</div><div id="reward" class="card reward"><?php if($signedIn): ?><strong>Signed in:</strong> downloading can add today’s +<?=intval($stencil['reward_bits'])?> bit$ to your wallet.<?php else: ?>Today’s generated stencil set is public and free. <a style="color:#fff" href="../beyond-id/auth/login.php">Sign in</a> only for the optional +<?=intval($stencil['reward_bits'])?> bit$ reward.<?php endif; ?></div><div class="card link-box">Official link: <a href="<?=htmlspecialchars($stencil['public_url'])?>"><?=htmlspecialchars(preg_replace('#^https?://#','',$stencil['public_url']))?></a></div><p class="legal">For personal practice, Canvas previews, and licensed use. Artists remain responsible for final sizing, sanitation, placement, and local professional requirements.</p></div><div class="card preview"><div class="date-badge"><span>THURSDAY</span>JULY 16<br>2026</div><img class="stencil" src="<?=htmlspecialchars($stencil['preview_url'])?>?v=<?=urlencode((string)$stencil['updated_at'])?>" alt="<?=htmlspecialchars($stencil['title'])?> tattoo stencil for Thursday July 16, 2026"></div></section><section class="features"><article class="card feature"><h3>Public access</h3><p>Open and download the current generated stencil set without creating an account.</p></article><article class="card feature"><h3>Advanced editing</h3><p>Mirror, rotate, resize, tune line weight, add placement guides, and prepare for transfer printing.</p></article><article class="card feature"><h3>Print or save PDF</h3><p>Use the dedicated print layout and choose “Save as PDF” from your device’s print dialog.</p></article></section><section class="card promo"><img src="<?=htmlspecialchars($stencil['preview_url'])?>?v=<?=urlencode((string)$stencil['updated_at'])?>" alt="Beyond Tattoo generated Stencil of the Day preview"></section></main>
<script>
const signedIn=<?= $signedIn ? 'true':'false' ?>;const reward=document.getElementById('reward');document.getElementById('downloadBtn').addEventListener('click',()=>{if(!signedIn)return;const body=new URLSearchParams({csrf:<?=json_encode($_SESSION['stencil_csrf'])?>});fetch('api/stencil-reward.php',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body}).then(r=>r.json()).then(d=>{reward.textContent=d.message||'Download ready.'}).catch(()=>{reward.textContent='The generated stencil set is still free. Reward sync is temporarily unavailable.'})});
</script></body></html>
