<?php
declare(strict_types=1);
require_once __DIR__ . '/../includes/ecosystem.php';
$beyondWallet = beyond_app_bootstrap('Beyond Math');
$userName = $_SESSION['user_name'] ?? $_SESSION['name'] ?? 'Learner';
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#07111f"><title>Beyond Math Dashboard</title><link rel="stylesheet" href="/beyond-math/assets/css/style.css?v=2.1"></head>
<body class="dashboard-page"><header class="site-header"><a class="brand" href="/beyond-math/"><span>Beyond Math <b>× Academy</b></span></a><nav class="nav"><a href="/beyond-math/academy.php">Learn</a><a href="/beyond-math/tools.php">Tools</a><a href="/academy/">Academy</a></nav></header>
<main class="dashboard-shell section-pad"><section class="dashboard-welcome"><div><p class="eyebrow">Your learning dashboard</p><h1>Welcome back, <?= htmlspecialchars((string)$userName, ENT_QUOTES, 'UTF-8') ?>.</h1><p class="muted">Continue where you left off or choose a quick practice activity.</p></div><div class="streak-pill">7-day streak 🔥</div></section>
<section class="continue-card"><div><small>CONTINUE LEARNING</small><h2>Algebra Foundations</h2><p>Solving two-step equations · 68% complete</p><div class="progress"><span style="width:68%"></span></div></div><div class="continue-actions"><a class="btn primary" href="/beyond-math/academy.php">Continue lesson</a><a class="btn secondary" href="/beyond-math/academy.php#practice">Practice again</a></div></section>
<div class="dashboard-grid"><section class="dash-card"><h3>Learning paths</h3><a href="/beyond-math/academy.php">Algebra</a><a href="/beyond-math/academy.php">Geometry</a><a href="/beyond-math/academy.php">Statistics</a><a href="/beyond-math/academy.php">Coding math</a></section><section class="dash-card"><h3>Daily challenge</h3><p>Complete three focused questions.</p><strong>+25 Bit$</strong><a class="btn primary" href="/beyond-math/academy.php">Start challenge</a></section><section class="dash-card"><h3>AI Math Coach</h3><p>Get a hint, upload a worksheet or ask for a simpler explanation.</p><button class="btn secondary" type="button" disabled>Coach preview</button></section><section class="dash-card"><h3>Your progress</h3><dl><div><dt>Accuracy</dt><dd>84%</dd></div><div><dt>Lessons</dt><dd>12</dd></div><div><dt>Weekly time</dt><dd>2h 18m</dd></div></dl></section></div>
<section class="tool-strip"><h2>Math tools</h2><div><a href="/beyond-math/tools.php#scientific">Scientific calculator</a><a href="/beyond-math/tools.php#fractions">Fractions</a><a href="/beyond-math/tools.php#geometry">Geometry formulas</a><a href="/beyond-math/tools.php#converter">Unit converter</a></div></section></main></body></html>
