<?php
declare(strict_types=1);
require __DIR__.'/bootstrap.php';require_once dirname(__DIR__,3).'/config/bootstrap.php';
$message='';$error='';$file=beyond_private_root().'/config/live.php';$cfg=beyond_live_config();
function french_setpath(array &$a,array $parts,$value):void{$r=&$a;foreach($parts as $i=>$p){if($i===count($parts)-1){$r[$p]=$value;return;}if(!isset($r[$p])||!is_array($r[$p]))$r[$p]=[];$r=&$r[$p];}}
if($_SERVER['REQUEST_METHOD']==='POST'){if(!Auth::verifyCsrf($_POST['csrf']??null)){$error='Invalid security token.';}else try{$dialect=in_array($_POST['dialect']??'', ['fr-FR','fr-CA'],true)?$_POST['dialect']:'fr-CA';$level=in_array($_POST['level']??'', ['beginner','intermediate','advanced'],true)?$_POST['level']:'beginner';french_setpath($cfg,['french','dialect'],$dialect);french_setpath($cfg,['french','default_level'],$level);french_setpath($cfg,['french','items_per_page'],max(5,min(50,(int)($_POST['items_per_page']??12))));french_setpath($cfg,['french','auto_narration'],!empty($_POST['auto_narration']));french_setpath($cfg,['french','show_phonetics'],!empty($_POST['show_phonetics']));$php="<?php\ndeclare(strict_types=1);\n/* Protected live configuration. Keep beside public_html. */\nreturn ".var_export($cfg,true).";\n";$tmp=$file.'.tmp';if(file_put_contents($tmp,$php,LOCK_EX)===false||!rename($tmp,$file))throw new RuntimeException('Could not save protected configuration.');@chmod($file,0600);$message='Beyond French options saved.';}catch(Throwable $exception){error_log($exception->getMessage());$error='Options could not be saved.';}}
require dirname(__DIR__).'/_header.php';?>
<link rel="stylesheet" href="/server/admin/daily-studio/studio.css"><link rel="stylesheet" href="/server/admin/daily-studio/studio-sunset.css"><div class="studio-head"><div><p class="studio-eyebrow">Beyond French</p><h1>Page Options</h1><p class="muted">Defaults used by the French generator and learning pages.</p></div></div><?php if($message):?><div class="alert studio-ok"><?=DailyStudio::esc($message)?></div><?php endif;?><?php if($error):?><div class="alert danger"><?=DailyStudio::esc($error)?></div><?php endif;?>
<form method="post" class="card"><input type="hidden" name="csrf" value="<?=DailyStudio::esc(Auth::csrf())?>"><div class="two"><div class="field"><label>Default dialect</label><select class="input" name="dialect"><option value="fr-CA" <?=beyond_config('french.dialect','fr-CA')==='fr-CA'?'selected':''?>>Canadian French</option><option value="fr-FR" <?=beyond_config('french.dialect','fr-CA')==='fr-FR'?'selected':''?>>France French</option></select></div><div class="field"><label>Default level</label><select class="input" name="level"><?php foreach(['beginner','intermediate','advanced'] as $level):?><option value="<?=$level?>" <?=beyond_config('french.default_level','beginner')===$level?'selected':''?>><?=ucfirst($level)?></option><?php endforeach;?></select></div></div><div class="field"><label>Items per page</label><input class="input" type="number" name="items_per_page" min="5" max="50" value="<?=(int)beyond_config('french.items_per_page',12)?>"></div><label><input type="checkbox" name="auto_narration" value="1" <?=beyond_config('french.auto_narration',false)?'checked':''?>> Generate narration with new content</label><br><label><input type="checkbox" name="show_phonetics" value="1" <?=beyond_config('french.show_phonetics',true)?'checked':''?>> Show phonetic guidance</label><p><button class="btn" type="submit">Save Beyond French options</button></p></form><?php require dirname(__DIR__).'/_footer.php';?>
