<?php
declare(strict_types=1);

require_once __DIR__.'/../config/bootstrap.php';
if(session_status()!==PHP_SESSION_ACTIVE){session_set_cookie_params(['httponly'=>true,'secure'=>!empty($_SERVER['HTTPS']),'samesite'=>'Lax']);session_start();}
if(!isset($academyConfig)||!is_array($academyConfig))throw new RuntimeException('Academy configuration is required.');

function la_h(string $value): string{return htmlspecialchars($value,ENT_QUOTES,'UTF-8');}
function la_slug(string $value): string{$slug=strtolower(trim((string)preg_replace('/[^a-z0-9]+/i','-',$value),'-'));return $slug!==''?$slug:'module';}
function la_ages(): array{return [
 'preschool'=>['title'=>'Preschool','ages'=>'3–5','icon'=>'🧸','guide'=>'Short, visual, playful practice with a grown-up helper.'],
 'kids'=>['title'=>'Kids','ages'=>'6–9','icon'=>'🎨','guide'=>'Clear examples, short challenges, and hands-on learning.'],
 'preteen'=>['title'=>'Preteen','ages'=>'10–12','icon'=>'🚀','guide'=>'Real-life problems, independent practice, and creative projects.'],
 'teen'=>['title'=>'Teen','ages'=>'13–17','icon'=>'🎧','guide'=>'Deeper reasoning, practical application, and portfolio-ready challenges.'],
 'adult'=>['title'=>'Adult','ages'=>'18+','icon'=>'☕','guide'=>'Useful skills for daily life, work, confidence, and continued learning.']
];}
function la_groups(array $config): array{$groups=$config['paths']??null;return is_array($groups)&&$groups!==[]?$groups:la_ages();}
function la_age(string $age,array $config=[]): string{$age=strtolower(trim($age));$groups=la_groups($config);if(isset($groups[$age]))return $age;$default=(string)($config['default_path']??'kids');return isset($groups[$default])?$default:(string)array_key_first($groups);}
function la_phases(): array{return [
 ['Discover','Learn the core idea and connect it to something familiar.','Explain the idea in one clear sentence.'],
 ['Vocabulary','Learn the important words, symbols, or tools for this topic.','Match each new term to its meaning or purpose.'],
 ['Guided Example','Follow a complete example one step at a time.','Repeat the example and explain why each step works.'],
 ['Skill Builder','Practice the main skill with supportive prompts.','Complete three short practice rounds without rushing.'],
 ['Patterns','Notice relationships, repeated structures, and useful clues.','Find and describe two patterns in the topic.'],
 ['Real Life','Apply the skill to an everyday decision or situation.','Use the skill in one realistic scenario.'],
 ['Problem Solving','Choose a strategy, test it, and adjust when needed.','Solve a new challenge and record your reasoning.'],
 ['Create','Turn the skill into a small project, demonstration, or plan.','Build a mini project that shows what you understand.'],
 ['Explain','Teach the idea back in your own words and answer questions.','Give a one-minute explanation without reading notes.'],
 ['Mastery','Review the full topic and prepare for the module exam.','Complete a final mixed challenge and identify what to review.']
];}
function la_modules(array $config,string $age): array{
 $titles=(array)($config['tracks'][$age]??$config['tracks']['kids']??[]);$modules=[];
 foreach(array_values($titles) as $index=>$item){$title=is_array($item)?(string)($item['title']??'Module'):strval($item);$description=is_array($item)?(string)($item['description']??''):'Build practical, age-appropriate skills in '.$title.' through examples, practice, and a final project.';$lessons=[];
  foreach(la_phases() as $lessonIndex=>$phase)$lessons[]=['number'=>$lessonIndex+1,'title'=>$phase[0].': '.$title,'focus'=>$phase[0],'teaching'=>$phase[1].' '.$description,'practice'=>$phase[2]];
  $modules[]=['number'=>$index+1,'slug'=>la_slug($title),'title'=>$title,'description'=>$description,'free'=>$index===0,'lessons'=>$lessons];
 }
 return $modules;
}
function la_module(array $config,string $age,string $slug): ?array{foreach(la_modules($config,$age) as $module)if($module['slug']===$slug||$module['number']===(int)$slug)return $module;return null;}
function la_db(): PDO{static $pdo=null;if($pdo instanceof PDO)return $pdo;$path=beyond_private_root().'/learning-academy.sqlite';$pdo=new PDO('sqlite:'.$path,null,null,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);$pdo->exec('PRAGMA busy_timeout=5000; PRAGMA journal_mode=WAL;');$pdo->exec("CREATE TABLE IF NOT EXISTS learning_academy_progress(app_slug TEXT NOT NULL,learner_key TEXT NOT NULL,age_group TEXT NOT NULL,module_slug TEXT NOT NULL,lesson_number INTEGER NOT NULL,best_score INTEGER NOT NULL DEFAULT 0,passed INTEGER NOT NULL DEFAULT 0,completed_at TEXT NULL,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(app_slug,learner_key,age_group,module_slug,lesson_number))");$pdo->exec("CREATE TABLE IF NOT EXISTS learning_academy_attempts(id INTEGER PRIMARY KEY AUTOINCREMENT,app_slug TEXT NOT NULL,learner_key TEXT NOT NULL,age_group TEXT NOT NULL,module_slug TEXT NOT NULL,assessment_type TEXT NOT NULL,lesson_number INTEGER NULL,score INTEGER NOT NULL,question_count INTEGER NOT NULL DEFAULT 10,passed INTEGER NOT NULL DEFAULT 0,attempted_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)");$pdo->exec('CREATE INDEX IF NOT EXISTS idx_learning_attempts ON learning_academy_attempts(app_slug,learner_key,age_group,module_slug,assessment_type)');return $pdo;}
function la_learner(): string{$user=(int)($_SESSION['user_id']??0);if($user>0)return 'u:'.$user;if(empty($_SESSION['learning_academy_key']))$_SESSION['learning_academy_key']=bin2hex(random_bytes(16));return 's:'.$_SESSION['learning_academy_key'];}
function la_full_access(): bool{$role=strtolower((string)($_SESSION['role']??''));return !empty($_SESSION['user_id'])||in_array($role,['admin','super_admin'],true)||!empty($_SESSION['learning_academy_entitled']);}
function la_admin(): bool{$role=strtolower((string)($_SESSION['role']??''));return in_array($role,['admin','super_admin'],true);}
function la_lesson_passed(string $app,string $age,string $module,int $lesson): bool{$s=la_db()->prepare('SELECT passed FROM learning_academy_progress WHERE app_slug=? AND learner_key=? AND age_group=? AND module_slug=? AND lesson_number=?');$s->execute([$app,la_learner(),$age,$module,$lesson]);return (int)$s->fetchColumn()===1;}
function la_exam_passed(string $app,string $age,string $module): bool{$s=la_db()->prepare("SELECT 1 FROM learning_academy_attempts WHERE app_slug=? AND learner_key=? AND age_group=? AND module_slug=? AND assessment_type='exam' AND passed=1 LIMIT 1");$s->execute([$app,la_learner(),$age,$module]);return (bool)$s->fetchColumn();}
function la_lesson_unlocked(array $config,string $age,array $module,int $lesson): bool{if(la_admin())return true;if(!$module['free']&&!la_full_access())return false;if($lesson>1)return la_lesson_passed($config['slug'],$age,$module['slug'],$lesson-1);if($module['number']===1)return true;$modules=la_modules($config,$age);return la_exam_passed($config['slug'],$age,$modules[$module['number']-2]['slug']);}
function la_progress(string $app,string $age,string $module): array{$s=la_db()->prepare('SELECT COUNT(*) count,COALESCE(MAX(best_score),0) best FROM learning_academy_progress WHERE app_slug=? AND learner_key=? AND age_group=? AND module_slug=? AND passed=1');$s->execute([$app,la_learner(),$age,$module]);$r=$s->fetch()?:[];return ['count'=>(int)($r['count']??0),'best'=>(int)($r['best']??0),'exam'=>la_exam_passed($app,$age,$module)];}
function la_options(string $correct,array $pool,int $seed): array{$all=array_values(array_unique(array_filter([$correct,...$pool])));while(count($all)<4)$all[]='Review the lesson '.(count($all)+1);$all=array_slice($all,0,4);$shift=$seed%4;return array_values([...array_slice($all,$shift),...array_slice($all,0,$shift)]);}
function la_test_questions(array $config,string $age,array $module,int $lesson): array{$ages=la_groups($config);$item=$module['lessons'][$lesson-1];$others=[];for($i=1;$i<=3;$i++)$others[]=$module['lessons'][($lesson-1+$i)%10];$modulePool=array_map(fn($m)=>$m['title'],array_slice(la_modules($config,$age),0,4));$focusPool=array_column($others,'focus');$teachPool=array_column($others,'teaching');$practicePool=array_column($others,'practice');$titlePool=array_column($others,'title');return [
 ['q'=>'Which course module are you studying?','a'=>$module['title'],'o'=>la_options($module['title'],$modulePool,$lesson)],
 ['q'=>'Which lesson is the focus right now?','a'=>$item['title'],'o'=>la_options($item['title'],$titlePool,$lesson+1)],
 ['q'=>'What is the main learning stage in this lesson?','a'=>$item['focus'],'o'=>la_options($item['focus'],$focusPool,$lesson+2)],
 ['q'=>'Choose the teaching statement from this lesson.','a'=>$item['teaching'],'o'=>la_options($item['teaching'],$teachPool,$lesson+3)],
 ['q'=>'Choose the practice action assigned in this lesson.','a'=>$item['practice'],'o'=>la_options($item['practice'],$practicePool,$lesson+4)],
 ['q'=>'Which learning path is this lesson designed for?','a'=>$ages[$age]['title'],'o'=>la_options($ages[$age]['title'],array_column($ages,'title'),$lesson+5)],
 ['q'=>'What is the lesson number?','a'=>(string)$lesson,'o'=>la_options((string)$lesson,[(string)(($lesson%10)+1),(string)max(1,$lesson-1),(string)min(10,$lesson+2)],$lesson+6)],
 ['q'=>'What should happen before moving to the next lesson?','a'=>'Pass this lesson test','o'=>la_options('Pass this lesson test',['Skip the practice','Open the final exam immediately','Change age groups'],$lesson+7)],
 ['q'=>'What score is required to pass?','a'=>'8 out of 10','o'=>la_options('8 out of 10',['5 out of 10','6 out of 10','10 out of 10'],$lesson+8)],
 ['q'=>'Which learning order is used?','a'=>'Learn, practice, test','o'=>la_options('Learn, practice, test',['Test, skip, finish','Guess, submit, leave','Read, ignore, advance'],$lesson+9)]
 ];}
function la_exam_questions(array $module): array{$questions=[];$titles=array_column($module['lessons'],'title');foreach($module['lessons'] as $i=>$lesson){$pool=[];for($j=1;$j<=3;$j++)$pool[]=$titles[($i+$j)%10];$questions[]=['q'=>'Which lesson matches this practice: '.$lesson['practice'],'a'=>$lesson['title'],'o'=>la_options($lesson['title'],$pool,$i+1)];}return $questions;}
function la_score(array $questions,array $answers): int{$score=0;foreach($questions as $i=>$q)if(trim((string)($answers[$i]??''))===trim((string)$q['a']))$score++;return $score;}
function la_record_test(array $config,string $age,array $module,int $lesson,int $score): bool{$passed=$score>=8;$pdo=la_db();$pdo->prepare("INSERT INTO learning_academy_attempts(app_slug,learner_key,age_group,module_slug,assessment_type,lesson_number,score,passed) VALUES(?,?,?,?, 'lesson',?,?,?)")->execute([$config['slug'],la_learner(),$age,$module['slug'],$lesson,$score,$passed?1:0]);$pdo->prepare("INSERT INTO learning_academy_progress(app_slug,learner_key,age_group,module_slug,lesson_number,best_score,passed,completed_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(app_slug,learner_key,age_group,module_slug,lesson_number) DO UPDATE SET best_score=MAX(best_score,excluded.best_score),passed=MAX(passed,excluded.passed),completed_at=CASE WHEN excluded.passed=1 THEN CURRENT_TIMESTAMP ELSE completed_at END,updated_at=CURRENT_TIMESTAMP")->execute([$config['slug'],la_learner(),$age,$module['slug'],$lesson,$score,$passed?1:0,$passed?date(DATE_ATOM):null]);return $passed;}
function la_record_exam(array $config,string $age,array $module,int $score): bool{$passed=$score>=8;la_db()->prepare("INSERT INTO learning_academy_attempts(app_slug,learner_key,age_group,module_slug,assessment_type,score,passed) VALUES(?,?,?,?, 'exam',?,?)")->execute([$config['slug'],la_learner(),$age,$module['slug'],$score,$passed?1:0]);return $passed;}
function la_csrf(): string{if(empty($_SESSION['learning_academy_csrf']))$_SESSION['learning_academy_csrf']=bin2hex(random_bytes(32));return $_SESSION['learning_academy_csrf'];}
function la_verify(): bool{return isset($_POST['csrf'])&&hash_equals((string)($_SESSION['learning_academy_csrf']??''),(string)$_POST['csrf']);}

$laAge=la_age((string)($_GET['age']??$_POST['age']??$_SESSION[$academyConfig['slug'].'_age']??''),$academyConfig);$_SESSION[$academyConfig['slug'].'_age']=$laAge;$laView=(string)($_GET['view']??'home');$laModule=la_module($academyConfig,$laAge,(string)($_GET['module']??$_POST['module']??'1'));$laLesson=max(1,min(10,(int)($_GET['lesson']??$_POST['lesson']??1)));$laResult=null;
$laAssessmentAllowed=$laModule&&($laView==='test'?la_lesson_unlocked($academyConfig,$laAge,$laModule,$laLesson):($laView==='exam'?(la_progress($academyConfig['slug'],$laAge,$laModule['slug'])['count']===10||la_admin()):true));
if($_SERVER['REQUEST_METHOD']==='POST'&&$laModule&&in_array($laView,['test','exam'],true)){if(!$laAssessmentAllowed){http_response_code(403);$laResult=['score'=>0,'passed'=>false,'error'=>'Assessment locked.'];}elseif(!la_verify())$laResult=['score'=>0,'passed'=>false,'error'=>'Session expired.'];else{$questions=$laView==='test'?la_test_questions($academyConfig,$laAge,$laModule,$laLesson):la_exam_questions($laModule);$score=la_score($questions,(array)($_POST['answers']??[]));$passed=$laView==='test'?la_record_test($academyConfig,$laAge,$laModule,$laLesson,$score):la_record_exam($academyConfig,$laAge,$laModule,$score);$laResult=['score'=>$score,'passed'=>$passed];}}
$laBase=(string)$academyConfig['base'];$laCss=(string)($academyConfig['css']??'/assets/css/learning-academy.css');$laGroups=la_groups($academyConfig);$laGroupLabel=(string)($academyConfig['group_label']??'age paths');
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=la_h($academyConfig['title'])?></title><meta name="description" content="<?=la_h($academyConfig['description'])?>"><link rel="stylesheet" href="<?=la_h($laCss)?>"></head><body style="--academy-accent:<?=la_h($academyConfig['accent'])?>"><header class="la-nav"><a class="la-brand" href="<?=la_h($laBase)?>"><span><?=la_h($academyConfig['icon'])?></span><strong><?=la_h($academyConfig['title'])?></strong></a><nav><a href="<?=la_h($laBase)?>">Academy</a><a href="/dashboard/">Beyond ID</a><a href="/">Beyond Home</a></nav></header><main class="la-main">
<?php if($laView==='home'): $modules=la_modules($academyConfig,$laAge);?>
<section class="la-hero"><span class="la-kicker">LIVE · LEARN · EARN</span><h1><?=la_h($academyConfig['headline'])?></h1><p><?=la_h($academyConfig['description'])?></p><div class="la-stats"><div><b><?=count($laGroups)?></b><span><?=la_h($laGroupLabel)?></span></div><div><b>5</b><span>modules</span></div><div><b>50</b><span>lessons</span></div><div><b>55</b><span>assessments</span></div></div></section><nav class="la-ages"><?php foreach($laGroups as $slug=>$age):?><a class="<?=$slug===$laAge?'active':''?>" href="?age=<?=la_h($slug)?>"><?=la_h($age['icon'].' '.$age['title'])?><small><?=la_h($age['ages'])?></small></a><?php endforeach;?></nav><p class="la-guide"><strong><?=la_h($laGroups[$laAge]['title'])?>:</strong> <?=la_h($laGroups[$laAge]['guide'])?> Module 1 is free.</p><section class="la-grid"><?php foreach($modules as $module):$p=la_progress($academyConfig['slug'],$laAge,$module['slug']);$access=$module['free']||la_full_access();?><article class="la-card"><div class="la-card-top"><span class="la-num">0<?=$module['number']?></span><span class="la-badge <?=$module['free']?'free':($access?'':'locked')?>"><?=$module['free']?'Free':($access?'Member':'Locked')?></span></div><h2><?=la_h($module['title'])?></h2><p><?=la_h($module['description'])?></p><div class="la-progress"><span style="width:<?=$p['count']*10?>%"></span></div><footer><small><?=$p['count']?>/10 lessons · <?=$p['exam']?'Exam passed':'Exam pending'?></small><a class="la-button <?=$access?'':'disabled'?>" href="?view=module&age=<?=la_h($laAge)?>&module=<?=la_h($module['slug'])?>"><?=$access?'Open':'Members'?></a></footer></article><?php endforeach;?></section>
<?php elseif($laModule&&$laView==='module'): $access=$laModule['free']||la_full_access();$p=la_progress($academyConfig['slug'],$laAge,$laModule['slug']);?>
<a class="la-back" href="?age=<?=la_h($laAge)?>">← All modules</a><?php if(!$access):?><section class="la-lock"><h1>🔒 Member module</h1><p>Module 1 is free for every learning path. Sign in with Beyond ID to access the full academy.</p><a class="la-button" href="?age=<?=la_h($laAge)?>">Open free module</a></section><?php else:?><section class="la-title"><span class="la-kicker"><?=la_h($laGroups[$laAge]['title'])?> · MODULE <?=$laModule['number']?></span><h1><?=la_h($laModule['title'])?></h1><p><?=la_h($laModule['description'])?></p></section><section class="la-list"><?php foreach($laModule['lessons'] as $lesson):$passed=la_lesson_passed($academyConfig['slug'],$laAge,$laModule['slug'],$lesson['number']);$unlocked=la_lesson_unlocked($academyConfig,$laAge,$laModule,$lesson['number']);?><article class="la-row <?=$unlocked?'':'locked'?>"><span><?=$lesson['number']?></span><div><h3><?=la_h($lesson['title'])?></h3><p>Guided lesson · 10-question test</p></div><?php if($unlocked):?><a class="la-button secondary" href="?view=lesson&age=<?=la_h($laAge)?>&module=<?=la_h($laModule['slug'])?>&lesson=<?=$lesson['number']?>"><?=$passed?'Review':'Start'?></a><?php else:?><b>Locked</b><?php endif;?></article><?php endforeach;?></section><section class="la-exam"><h2>Module Exam</h2><p>Complete all 10 lesson tests, then score 8/10 on the exam.</p><a class="la-button <?=$p['count']===10?'':'disabled'?>" href="?view=exam&age=<?=la_h($laAge)?>&module=<?=la_h($laModule['slug'])?>"><?=$p['exam']?'Review exam':($p['count']===10?'Take exam':'Complete lessons')?></a></section><?php endif;?>
<?php elseif($laModule&&$laView==='lesson'&&la_lesson_unlocked($academyConfig,$laAge,$laModule,$laLesson)): $item=$laModule['lessons'][$laLesson-1];?>
<a class="la-back" href="?view=module&age=<?=la_h($laAge)?>&module=<?=la_h($laModule['slug'])?>">← <?=la_h($laModule['title'])?></a><article class="la-reading"><span class="la-kicker"><?=la_h($laGroups[$laAge]['title'])?> · LESSON <?=$laLesson?></span><h1><?=la_h($item['title'])?></h1><section><h2>Learn</h2><p><?=la_h($item['teaching'])?></p></section><div class="la-two"><section><h2>Practice</h2><p><?=la_h($item['practice'])?></p></section><section><h2>Reflect</h2><p>What changed in your understanding? Explain one example in your own words.</p></section></div><?php if(!empty($academyConfig['disclaimer'])):?><p class="la-disclaimer"><?=la_h($academyConfig['disclaimer'])?></p><?php endif;?><a class="la-button" href="?view=test&age=<?=la_h($laAge)?>&module=<?=la_h($laModule['slug'])?>&lesson=<?=$laLesson?>">Take lesson test →</a></article>
<?php elseif($laModule&&in_array($laView,['test','exam'],true)&&$laAssessmentAllowed): $questions=$laView==='test'?la_test_questions($academyConfig,$laAge,$laModule,$laLesson):la_exam_questions($laModule);?>
<a class="la-back" href="?view=module&age=<?=la_h($laAge)?>&module=<?=la_h($laModule['slug'])?>">← <?=la_h($laModule['title'])?></a><section class="la-title"><span class="la-kicker"><?=$laView==='exam'?'MODULE EXAM':'LESSON TEST'?></span><h1><?=$laView==='exam'?la_h($laModule['title']):la_h($laModule['lessons'][$laLesson-1]['title'])?></h1><p>Answer 10 questions. A score of 8/10 is required.</p></section><?php if($laResult):?><div class="la-result <?=$laResult['passed']?'pass':''?>"><h2><?=$laResult['passed']?'Passed!':'Review and try again'?></h2><p>Score: <strong><?=$laResult['score']?>/10</strong></p></div><?php endif;?><form class="la-quiz" method="post"><input type="hidden" name="csrf" value="<?=la_h(la_csrf())?>"><input type="hidden" name="age" value="<?=la_h($laAge)?>"><input type="hidden" name="module" value="<?=la_h($laModule['slug'])?>"><input type="hidden" name="lesson" value="<?=$laLesson?>"><?php foreach($questions as $i=>$q):?><fieldset><legend><?=($i+1)?>. <?=la_h($q['q'])?></legend><?php foreach($q['o'] as $option):?><label><input type="radio" name="answers[<?=$i?>]" value="<?=la_h((string)$option)?>" required><span><?=la_h((string)$option)?></span></label><?php endforeach;?></fieldset><?php endforeach;?><button class="la-button" type="submit">Submit <?=$laView==='exam'?'exam':'test'?></button></form>
<?php else:?><section class="la-lock"><h1>Lesson locked</h1><p>Complete the previous assessment to continue.</p><a class="la-button" href="?age=<?=la_h($laAge)?>">Return to academy</a></section><?php endif;?></main><footer class="la-footer"><strong><?=la_h($academyConfig['title'])?></strong><span>5 modules · 10 lessons each · Learn responsibly</span></footer></body></html>
