<?php
declare(strict_types=1);
require_once __DIR__.'/../beyond-id/includes/db.php';require_once __DIR__.'/includes/academy-stripe.php';
$payload=(string)file_get_contents('php://input');$signature=(string)($_SERVER['HTTP_STRIPE_SIGNATURE']??'');$secret=academy_stripe_webhook_secret();if($secret===''||!academy_verify_stripe_signature($payload,$signature,$secret)){http_response_code(400);exit('Invalid signature.');}
$event=json_decode($payload,true);if(!is_array($event)||empty($event['id'])){http_response_code(400);exit('Invalid payload.');}$eventId=(string)$event['id'];$type=(string)($event['type']??'unknown');
try{$driver=$pdo->getAttribute(PDO::ATTR_DRIVER_NAME);$insert=$driver==='sqlite'?'INSERT OR IGNORE INTO academy_stripe_events(stripe_event_id,event_type,payload_json) VALUES(?,?,?)':'INSERT IGNORE INTO academy_stripe_events(stripe_event_id,event_type,payload_json) VALUES(?,?,?)';$pdo->prepare($insert)->execute([$eventId,$type,$payload]);$q=$pdo->prepare('SELECT processed FROM academy_stripe_events WHERE stripe_event_id=?');$q->execute([$eventId]);if((int)$q->fetchColumn()===1){http_response_code(200);exit('Already processed.');}$object=$event['data']['object']??[];
 if($type==='checkout.session.completed'){$userId=(int)($object['metadata']['user_id']??$object['client_reference_id']??0);if($userId)academy_upsert_subscription($pdo,$userId,(string)($object['customer']??''),(string)($object['subscription']??''),'active',null,null);}
 elseif(str_starts_with($type,'customer.subscription.')){$subscription=(string)($object['id']??'');$userId=(int)($object['metadata']['user_id']??0);if(!$userId&&$subscription!==''){$q=$pdo->prepare('SELECT user_id FROM academy_subscriptions WHERE provider_subscription_id=?');$q->execute([$subscription]);$userId=(int)$q->fetchColumn();}if($userId){$status=$type==='customer.subscription.deleted'?'canceled':(string)($object['status']??'expired');$start=!empty($object['current_period_start'])?date('Y-m-d H:i:s',(int)$object['current_period_start']):null;$end=!empty($object['current_period_end'])?date('Y-m-d H:i:s',(int)$object['current_period_end']):null;academy_upsert_subscription($pdo,$userId,(string)($object['customer']??''),$subscription,$status,$start,$end);}}
 $pdo->prepare('UPDATE academy_stripe_events SET processed=1,processed_at=CURRENT_TIMESTAMP,last_error=NULL WHERE stripe_event_id=?')->execute([$eventId]);http_response_code(200);echo 'ok';
}catch(Throwable $e){$pdo->prepare('UPDATE academy_stripe_events SET last_error=? WHERE stripe_event_id=?')->execute([$e->getMessage(),$eventId]);http_response_code(500);echo 'retry';}
