<?php
declare(strict_types=1);
if (session_status() !== PHP_SESSION_ACTIVE) { session_start(); }
require_once __DIR__ . '/includes/yugioh-live.php';
require_once __DIR__ . '/includes/beyond-cartoons-schedule.php';
require_once __DIR__ . '/includes/classic-schedule.php';
require_once __DIR__ . '/includes/space-schedule.php';
require_once __DIR__ . '/includes/movies-schedule.php';
require_once __DIR__ . '/includes/eight-channel-guide.php';

require_once __DIR__ . '/../includes/ecosystem.php';
if (!empty($_SESSION['user_id'])) { beyond_track_app('Beyond TV'); }
$channels=json_decode((string)file_get_contents(__DIR__.'/data/channels.json'),true)?:[];
$slug=(string)($_GET['slug']??''); $channel=null; foreach($channels as $candidate){if(($candidate['slug']??'')===$slug){$channel=$candidate;break;}}
if(!$channel){http_response_code(404);$channel=['name'=>'Channel not found','description'=>'This channel is unavailable.','icon'=>'📺','gradient'=>'linear-gradient(135deg,#222,#555)','now'=>'Unavailable','access'=>'guest'];}
$signedIn=!empty($_SESSION['user_id']);
if(($channel['access']??'guest')==='member'&&!$signedIn){$_SESSION['beyond_return_to']=$_SERVER['REQUEST_URI']??'/beyond-tv/';header('Location: /beyond-id/auth/login.php?required=1');exit;}
$isMoviesScheduled=(($channel['source_type']??'')==='scheduled_movies'); $moviesState=$isMoviesScheduled?beyond_movies_schedule_state():null;
$isAnimeChannel = $slug === 'yugioh-tv';
$animeHour = (int)(new DateTimeImmutable('now', new DateTimeZone('America/Vancouver')))->format('G');
$animeDay = (int)(new DateTimeImmutable('now', new DateTimeZone('America/Vancouver')))->format('z');
$isDragonBallBlock = $isAnimeChannel && $animeHour >= 0 && $animeHour < 3;
$isDragonBallKaiBlock = $isAnimeChannel && $animeHour >= 3 && $animeHour < 6;
$isDragonBallZBlock = $isAnimeChannel && (($animeHour >= 6 && $animeHour < 9) || $animeHour >= 21);
$isZatchBlock = $isAnimeChannel && $animeHour >= 12 && $animeHour < 15;
$isDigimonBlock = $isAnimeChannel && $animeHour >= 15 && $animeHour < 18;
$isPokemonBlock = $isAnimeChannel && $animeHour >= 18 && $animeHour < 21;
$zatchEpisode = (($animeHour * 2 + $animeDay) % 50) + 1;
$zatchEpisodeUrl = 'https://archive.org/download/zatch-bell-collection/Zatch%20Bell/Season%201/Zatch%20Bell%20S01E' . str_pad((string)$zatchEpisode, 2, '0', STR_PAD_LEFT) . '.mp4';
$animeMovieNumber = (($animeHour + $animeDay) % 2) + 1;
$animeMovieTitle = $animeMovieNumber === 1 ? 'Zatch Bell! Movie 1: 101st Devil' : 'Zatch Bell! Movie 2: Attack of the Mechavulcan';
$animeMovieUrl = $animeMovieNumber === 1 ? 'https://archive.org/download/zatch-bell-collection/Zatch%20Bell/Movies/Zatch%20Bell%20Movie%2001%20-%20%20Unlisted%20Demon%20101%20%28101st%20Devil%29.mp4' : 'https://archive.org/download/zatch-bell-collection/Zatch%20Bell/Movies/Zatch%20Bell%20Movie%2002%20-%20Attack%20of%20The%20Mechavulcan.mp4';
$digimonLibrary = json_decode((string)@file_get_contents(__DIR__.'/data/digimon-library.json'), true) ?: [];
$pokemonLibrary = json_decode((string)@file_get_contents(__DIR__.'/data/pokemon-library.json'), true) ?: [];
$dragonBallLibrary = json_decode((string)@file_get_contents(__DIR__.'/data/dragon-ball-library.json'), true) ?: [];
$dragonBallZLibrary = json_decode((string)@file_get_contents(__DIR__.'/data/dbz-westwood-sd-library.json'), true) ?: [];
$digimonEpisode = $digimonLibrary ? $digimonLibrary[((($animeHour-15)*2)+$animeDay)%count($digimonLibrary)] : [];
$pokemonEpisode = $pokemonLibrary ? $pokemonLibrary[((($animeHour-18)*2)+$animeDay)%count($pokemonLibrary)] : [];
$dragonBallEpisode = $dragonBallLibrary ? $dragonBallLibrary[(($animeHour*2)+$animeDay)%count($dragonBallLibrary)] : [];
$dragonBallZEpisode = $dragonBallZLibrary ? $dragonBallZLibrary[(($animeHour*2)+$animeDay)%count($dragonBallZLibrary)] : [];
$dragonBallKaiEpisodeNumber = (($animeHour * 2 + $animeDay) % 167) + 1;
$dragonBallKaiUrl = 'https://archive.org/download/dbkai/Dragon%20Ball%20Kai%20-%20' . str_pad((string)$dragonBallKaiEpisodeNumber, 2, '0', STR_PAD_LEFT) . '.mp4';
$digimonUrl = $digimonEpisode ? 'https://archive.org/download/digimon-digital-monsters-the-complete-collection-saban-entertainment-edited-version/'.rawurlencode((string)$digimonEpisode['file']) : '';
$pokemonUrl = $pokemonEpisode ? 'https://archive.org/download/pokemon-indigo-league-season-1-1998/'.rawurlencode((string)$pokemonEpisode['file']) : '';
$isAfterDarkCourage = $slug === 'beyond-after-dark' && ($animeHour >= 22 || in_array($animeHour, [4, 10, 16], true));
$courageEpisodeIndex = (($animeHour + $animeDay) % 13);
$courageEmbedUrl = 'https://www.youtube-nocookie.com/embed/videoseries?list=PLToQtMHGzmM0TTzBSVOfxrU-pgAZm6nlK&index=' . $courageEpisodeIndex . '&autoplay=1&mute=1&playsinline=1&rel=0';
$isClassic=($slug==='classic-cartoon-theater'); $isScheduled=(($channel['source_type']??'')==='scheduled_youtube'); $isSpaceScheduled=(($channel['source_type']??'')==='scheduled_space_youtube'); $scheduledState=$isScheduled?beyond_cartoons_schedule_state():($isSpaceScheduled?beyond_space_schedule_state():null); $isStream=!empty($channel['stream_endpoint']); $isExternal=!empty($channel['external_url']); $isPlaylistLive=(($channel['source_type']??'')==='youtube_playlist_live'); $isYouTubePlaylist=(($channel['source_type']??'')==='youtube_playlist_embed'); $isYouTube=(($channel['source_type']??'')==='youtube_embed'); $liveState=$isPlaylistLive?beyond_yugioh_live_state():null; $youtubeId=preg_replace('/[^A-Za-z0-9_-]/','',(string)($channel['youtube_id']??'')); $youtubeStart=max(0,(int)($channel['youtube_start']??0)); $youtubeAutoplay=!empty($channel['youtube_autoplay']); $youtubeMuted=!empty($channel['youtube_muted']); $youtubeParams=http_build_query(['autoplay'=>$youtubeAutoplay?1:0,'mute'=>$youtubeMuted?1:0,'playsinline'=>1,'rel'=>0,'modestbranding'=>1,'start'=>$youtubeStart]); $classicGuideState=beyond_classic_schedule_state(); $cartoonGuideState=beyond_cartoons_schedule_state(); $allGuideChannels=beyond_tv_eight_channel_guide($classicGuideState,$cartoonGuideState); $channelGuide=null; foreach($allGuideChannels as $g){if($g['slug']===$slug){$channelGuide=$g;break;}}
$youtubePlaylistId=preg_replace('/[^A-Za-z0-9_-]/','',(string)($channel['youtube_playlist_id']??'')); $youtubePlaylistVideoId=preg_replace('/[^A-Za-z0-9_-]/','',(string)($channel['youtube_playlist_video_id']??''));
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><script>(function(){try{const t=localStorage.getItem('beyond-tv-theme');document.documentElement.dataset.tvTheme=['dark','light','sunset'].includes(t)?t:'sunset';}catch(e){document.documentElement.dataset.tvTheme='sunset';}})();</script><title><?=htmlspecialchars((string)$channel['name'])?> | Beyond TV</title><link rel="stylesheet" href="/beyond-tv/assets/css/app.css?v=2.2.0"><style>.channel-page.shell{width:min(1440px,calc(100% - 28px))}.channel-page .player-shell{grid-template-columns:minmax(0,2.4fr) minmax(300px,.6fr);gap:24px}.channel-page .youtube-player-wrap,.channel-page .provider-player{min-height:0;aspect-ratio:16/9}.channel-page .youtube-player-wrap{border-radius:24px;box-shadow:0 28px 80px rgba(0,0,0,.42)}@media(max-width:980px){.channel-page .player-shell{grid-template-columns:1fr}.channel-page.shell{width:100%}.channel-page .app-back,.channel-page .channel-detail{margin-left:16px;margin-right:16px}.channel-page .youtube-player-wrap,.channel-page .provider-player{border-radius:0}}html[data-tv-theme="light"]{color-scheme:light}html[data-tv-theme="light"] body.tv-app{background:#eef2f8;color:#171a2e}html[data-tv-theme="light"] .channel-detail,html[data-tv-theme="light"] .schedule-mini>div{background:#fff!important;color:#171a2e;border-color:#dfe3ef!important}html[data-tv-theme="light"] .channel-detail p,html[data-tv-theme="light"] .schedule-mini small{color:#657087}.channel-theme-row{display:flex;justify-content:flex-end;margin:12px 16px}.channel-theme-toggle{min-height:42px;padding:0 14px;border-radius:12px;border:1px solid #3a3f55;background:#202438;color:#fff;font-weight:850;cursor:pointer}html[data-tv-theme="light"] .channel-theme-toggle{background:#fff;color:#171a2e;border-color:#cfd5e3}

html[data-tv-theme="sunset"]{color-scheme:dark}html[data-tv-theme="sunset"] .btv,html[data-tv-theme="sunset"] .classic-home,html[data-tv-theme="sunset"] body.tv-app{color:#fff7f2;background:radial-gradient(circle at 50% -10%,#7b2d58 0,#32133f 34%,#151326 72%)}html[data-tv-theme="sunset"] .btv:before{background:linear-gradient(180deg,rgba(78,25,70,.38),rgba(28,15,42,.88) 45%,#111325 80%)}html[data-tv-theme="sunset"] .btv-nav,html[data-tv-theme="sunset"] .classic-nav{background:rgba(40,17,43,.90);border-color:rgba(255,198,166,.18)}html[data-tv-theme="sunset"] .btv-btn,html[data-tv-theme="sunset"] .btv-theme-toggle,html[data-tv-theme="sunset"] .classic-btn,html[data-tv-theme="sunset"] .channel-theme-toggle{background:rgba(106,43,76,.45);border-color:rgba(255,205,176,.25);color:#fff7f2}html[data-tv-theme="sunset"] .now-panel,html[data-tv-theme="sunset"] .next-panel,html[data-tv-theme="sunset"] .live-chip,html[data-tv-theme="sunset"] .channel-switch,html[data-tv-theme="sunset"] .classic-info,html[data-tv-theme="sunset"] .guide-block,html[data-tv-theme="sunset"] .channel-card,html[data-tv-theme="sunset"] .release-note,html[data-tv-theme="sunset"] .channel-detail,html[data-tv-theme="sunset"] .schedule-mini>div{background:rgba(54,23,52,.90)!important;border-color:rgba(255,195,160,.20)!important;color:#fff7f2}html[data-tv-theme="sunset"] .epg{background:#2a1733;border-color:rgba(255,194,158,.20)}html[data-tv-theme="sunset"] .epg-cell{background:#321b3e;border-color:#5d3556;color:#fff7f2}html[data-tv-theme="sunset"] .epg-time,html[data-tv-theme="sunset"] .epg-channel,html[data-tv-theme="sunset"] .epg-corner{background:#402047;color:#ffd9c6}html[data-tv-theme="sunset"] .epg-program.current{background:#6e345e;box-shadow:inset 0 0 0 3px #ffb36b}html[data-tv-theme="sunset"] .channel-detail p,html[data-tv-theme="sunset"] .schedule-mini small,html[data-tv-theme="sunset"] .provider-status,html[data-tv-theme="sunset"] .clock-line{color:#e5bdb5}
</style></head><body class="tv-app">
<?php include __DIR__.'/partials/header.php'; ?>
<div class="channel-theme-row"><button class="channel-theme-toggle" type="button" data-tv-theme-toggle aria-label="Switch Beyond TV to light theme" aria-pressed="false">☀️ <span>Light</span></button></div><main class="page shell channel-page"><a class="back app-back" href="/beyond-tv/">← Back to channels</a>
<section class="player-shell real-channel">
<?php if($isClassic): ?><div class="youtube-player-wrap"><iframe class="youtube-player" src="<?=htmlspecialchars((string)$classicGuideState['embed_url'])?>" title="Classic Cartoon Theater live rotation" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe></div><div class="playlist-actions"><span class="source-pill">LIVE · VANCOUVER TIME</span><span><?=htmlspecialchars((string)$classicGuideState['current']['title'])?> · joins in progress</span></div>
<?php elseif(($isScheduled || $isSpaceScheduled) && $scheduledState): ?><div class="youtube-player-wrap"><iframe class="youtube-player" src="<?=htmlspecialchars((string)$scheduledState['embed_url'])?>" title="<?=htmlspecialchars((string)$channel['name'])?> synchronized live channel" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe></div><div class="playlist-actions"><span class="source-pill">LIVE · VANCOUVER TIME</span><span><?=htmlspecialchars((string)($scheduledState['playing']['title']??$scheduledState['current']['title']))?> · joins in progress</span></div>
<?php elseif($isMoviesScheduled && $moviesState): ?><div class="youtube-player-wrap"><iframe class="youtube-player" src="<?=htmlspecialchars((string)$moviesState['embed_url'])?>" title="Beyond Movies scheduled feature" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe></div><div class="playlist-actions"><span class="source-pill"><?=htmlspecialchars((string)$moviesState['label'])?></span><span><?=htmlspecialchars((string)$moviesState['current']['title'])?> · <?=htmlspecialchars((string)$moviesState['current']['genre'])?></span></div>
<?php elseif($isDragonBallBlock && $dragonBallEpisode): ?><div class="youtube-player-wrap"><video class="youtube-player" src="<?=htmlspecialchars((string)$dragonBallEpisode['video_url'])?>" controls autoplay muted playsinline></video></div><div class="playlist-actions"><span class="source-pill">BEYOND ANIME · LIVE</span><span>Dragon Ball · S1 E<?=intval($dragonBallEpisode['episode'])?> · <?=htmlspecialchars((string)$dragonBallEpisode['title'])?></span></div>
<?php elseif($isDragonBallKaiBlock): ?><div class="youtube-player-wrap"><video class="youtube-player" src="<?=htmlspecialchars($dragonBallKaiUrl)?>" controls autoplay muted playsinline></video></div><div class="playlist-actions"><span class="source-pill">BEYOND ANIME · LIVE</span><span>Dragon Ball Kai · Episode <?=$dragonBallKaiEpisodeNumber?></span></div>
<?php elseif($isDragonBallZBlock && $dragonBallZEpisode): ?><div class="youtube-player-wrap"><video class="youtube-player" src="<?=htmlspecialchars((string)$dragonBallZEpisode['video_url'])?>" controls autoplay muted playsinline></video></div><div class="playlist-actions"><span class="source-pill">BEYOND ANIME · SD LIVE</span><span>Dragon Ball Z · Episode <?=intval($dragonBallZEpisode['episode'])?> · <?=htmlspecialchars((string)$dragonBallZEpisode['title'])?></span></div>
<?php elseif($isZatchBlock): ?><div class="youtube-player-wrap"><video class="youtube-player" src="<?=htmlspecialchars($zatchEpisodeUrl)?>" controls autoplay muted playsinline></video></div><div class="playlist-actions"><span class="source-pill">BEYOND ANIME · LIVE</span><span>Zatch Bell! · Season 1 Episode <?=$zatchEpisode?></span></div>
<?php elseif($isDigimonBlock && $digimonEpisode): ?><div class="youtube-player-wrap"><video class="youtube-player" src="<?=htmlspecialchars($digimonUrl)?>" controls autoplay muted playsinline></video></div><div class="playlist-actions"><span class="source-pill">BEYOND ANIME · LIVE</span><span>Digimon · S<?=intval($digimonEpisode['season'])?> E<?=intval($digimonEpisode['episode'])?> · <?=htmlspecialchars((string)$digimonEpisode['title'])?></span></div>
<?php elseif($isPokemonBlock && $pokemonEpisode): ?><div class="youtube-player-wrap"><video class="youtube-player" src="<?=htmlspecialchars($pokemonUrl)?>" controls autoplay muted playsinline></video></div><div class="playlist-actions"><span class="source-pill">BEYOND ANIME · LIVE</span><span>Pokémon: Indigo League · S1 E<?=intval($pokemonEpisode['episode'])?> · <?=htmlspecialchars((string)$pokemonEpisode['title'])?></span></div>
<?php elseif($isPlaylistLive && $liveState): ?><div class="youtube-player-wrap"><iframe class="youtube-player" src="<?=htmlspecialchars((string)$liveState['embed_url'])?>" title="Beyond Anime synchronized Yu-Gi-Oh block" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe></div><div class="playlist-actions"><span class="source-pill">BEYOND ANIME · LIVE</span><span>Yu-Gi-Oh! Duel Monsters · Season 1 Episode <?= (int)$liveState['episode_number'] ?></span></div>
<?php elseif($isAfterDarkCourage): ?><div class="youtube-player-wrap"><iframe class="youtube-player" src="<?=htmlspecialchars($courageEmbedUrl)?>" title="Courage the Cowardly Dog After Dark rotation" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe></div><div class="playlist-actions"><span class="source-pill">AFTER DARK · LIVE</span><span>Courage the Cowardly Dog · Season 1 Episode <?=$courageEpisodeIndex+1?></span></div>
<?php elseif($isStream): ?><div class="provider-player" data-stream-endpoint="<?=htmlspecialchars((string)$channel['stream_endpoint'])?>"><video class="beyond-video" controls playsinline autoplay muted preload="metadata" poster="/beyond-tv/assets/img/beyond-tv-promo.webp"></video><div class="player-loading" role="status">Tuning in…</div><div class="player-fallback" hidden><p>Direct playback is unavailable.</p><button class="btn btn-secondary" type="button" data-open-embed>Open backup player</button></div><iframe class="archive-embed" title="Backup player" allow="autoplay; fullscreen" allowfullscreen hidden></iframe><button class="unmute-hint" type="button" data-unmute>🔊 Tap for sound</button></div>
<?php elseif($isYouTubePlaylist && $youtubePlaylistId): ?><div class="youtube-player-wrap"><iframe class="youtube-player" src="https://www.youtube-nocookie.com/embed/videoseries?list=<?=htmlspecialchars($youtubePlaylistId)?>&amp;autoplay=1&amp;mute=1&amp;playsinline=1&amp;rel=0" title="<?=htmlspecialchars((string)$channel['name'])?> movie playlist" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe></div><div class="playlist-actions"><a class="btn btn-secondary" href="https://www.youtube.com/playlist?list=<?=htmlspecialchars($youtubePlaylistId)?>" target="_blank" rel="noopener">▶ Open full movie playlist</a><span class="source-pill">YOUTUBE PLAYLIST</span></div>
<?php elseif($isYouTube && $youtubeId): ?><div class="youtube-player-wrap"><iframe class="youtube-player" src="https://www.youtube-nocookie.com/embed/<?=htmlspecialchars($youtubeId)?>?<?=htmlspecialchars($youtubeParams)?>" title="<?=htmlspecialchars((string)$channel['name'])?>" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe></div><?php if($youtubePlaylistId): ?><div class="playlist-actions"><a class="btn btn-secondary" href="https://www.youtube.com/watch?v=<?=htmlspecialchars($youtubePlaylistVideoId ?: $youtubeId)?>&amp;list=<?=htmlspecialchars($youtubePlaylistId)?>" target="_blank" rel="noopener">▶ Play Full Episode Playlist</a><span class="source-pill">YOUTUBE PLAYLIST</span></div><?php endif; ?>
<?php elseif($isYouTube): ?><div class="external-player series-ready" style="background:<?=$channel['gradient']?>"><span class="external-icon"><?=htmlspecialchars((string)$channel['icon'])?></span><span class="source-pill">OFFICIAL EMBED READY</span><h2>Add an approved episode</h2><p>This series page is ready. An administrator can paste an official YouTube video ID in TV Content Manager.</p><a class="btn btn-primary" href="<?=htmlspecialchars((string)($channel['official_url']??'#'))?>" target="_blank" rel="noopener">Browse <?=htmlspecialchars((string)($channel['official_channel']??'official channel'))?> ↗</a></div>
<?php elseif($isExternal): ?><div class="external-player" style="background:<?=$channel['gradient']?>"><span class="external-icon"><?=htmlspecialchars((string)$channel['icon'])?></span><h2>Official live source</h2><p>Beyond TV opens this channel from its official provider.</p><a class="btn btn-primary" href="<?=htmlspecialchars((string)$channel['external_url'])?>" target="_blank" rel="noopener">Open official stream ↗</a></div>
<?php else: ?><div class="video-placeholder" style="background:<?=$channel['gradient']?>"><span><?=htmlspecialchars((string)$channel['icon'])?></span></div><?php endif; ?>
<div class="channel-detail"><span class="live-badge">LIVE</span><?php if(!empty($channel['weekend'])):?><span class="weekend-badge">MEMBER PREVIEW</span><?php endif;?><h1><?=htmlspecialchars((string)$channel['name'])?></h1><p><?=htmlspecialchars((string)$channel['description'])?></p><p><strong>Now playing:</strong> <?=htmlspecialchars((string)($isMoviesScheduled ? $moviesState['current']['title'] : (($isScheduled || $isSpaceScheduled) ? (($scheduledState['current']['icon']??'').' '.($scheduledState['current']['title']??'')) : $channel['now'])))?></p><p><strong>Up next:</strong> <?=htmlspecialchars((string)($isMoviesScheduled ? $moviesState['next']['title'] : (($isScheduled || $isSpaceScheduled) ? ($scheduledState['next']['title']??'') : ($channel['up_next']??''))))?></p><?php if($channelGuide):?><div class="schedule-mini" style="display:grid;gap:8px;margin:18px 0"><?php foreach($channelGuide['rows'] as $block):?><div style="padding:10px 12px;border:1px solid #303446;border-radius:10px"><strong><?=htmlspecialchars((string)$block['icon'].' '.$block['title'])?></strong><br><small><?=htmlspecialchars((string)$block['lineup'])?></small></div><?php endforeach;?></div><?php endif;?><?php if($isPlaylistLive):?><p class="source-note"><span class="source-pill"><?=htmlspecialchars((string)($channel['source_label']??'YOUTUBE EMBED'))?></span></p><?php elseif($isYouTubePlaylist):?><p class="source-note"><span class="source-pill">YOUTUBE PLAYLIST</span></p><?php elseif($isYouTube && $youtubeId):?><p class="source-note"><span class="source-pill"><?=htmlspecialchars((string)($channel['source_label']??'YOUTUBE EMBED'))?></span></p><?php elseif($isExternal):?><p class="source-note"><span class="source-pill">OFFICIAL SOURCE</span></p><?php endif;?><?php if($signedIn):?><button class="btn btn-secondary" type="button" data-my-list>＋ My List</button><?php else:?><a class="btn btn-secondary" href="/beyond-id/auth/login.php?return=<?=urlencode($_SERVER['REQUEST_URI']??'/beyond-tv/')?>">Sign in to save</a><?php endif;?></div>
</section></main><script src="/beyond-tv/assets/js/app.js?v=2.2.0"></script><script>(function(){const root=document.documentElement,btn=document.querySelector('[data-tv-theme-toggle]'),themes=['dark','light','sunset'];if(!btn)return;function apply(t){if(!themes.includes(t))t='dark';root.dataset.tvTheme=t;const next=themes[(themes.indexOf(t)+1)%themes.length],icons={dark:'🌙',light:'☀️',sunset:'🌅'},labels={dark:'Dark',light:'Light',sunset:'Sunset'};btn.innerHTML=icons[t]+' <span>'+labels[t]+'</span>';btn.setAttribute('aria-label','Current theme '+labels[t]+'. Switch to '+labels[next]+' theme');btn.title='Switch to '+labels[next]+' theme';document.querySelector('meta[name=theme-color]')?.setAttribute('content',t==='light'?'#f4f6fb':t==='sunset'?'#32133f':'#080812');}apply(root.dataset.tvTheme||'sunset');btn.addEventListener('click',()=>{const current=themes.includes(root.dataset.tvTheme)?root.dataset.tvTheme:'dark',next=themes[(themes.indexOf(current)+1)%themes.length];try{localStorage.setItem('beyond-tv-theme',next)}catch(e){}apply(next)});})();</script><script src="/assets/js/visitor-analytics.js" defer></script></body></html>
