<?php
declare(strict_types=1);
require __DIR__.'/../includes/auth-check.php';
$uid=(int)$_SESSION['user_id'];$msg='';$err='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!verify_csrf_token($_POST['csrf']??null))$err='Session expired.';
 elseif(isset($_POST['revoke_session'])){try{$pdo->prepare('UPDATE user_sessions SET revoked_at=NOW() WHERE id=? AND user_id=?')->execute([(int)$_POST['revoke_session'],$uid]);$msg='Session revoked.';}catch(Throwable $e){$err='Run the Phase 2 migration to manage sessions.';}}
 elseif(isset($_POST['change_password'])){if(strlen($_POST['password']??'')<8)$err='Use at least eight characters.';elseif(($_POST['password']??'')!==($_POST['confirm']??''))$err='Passwords do not match.';else{$hash=password_hash($_POST['password'],PASSWORD_DEFAULT);$pdo->prepare('UPDATE users SET password=?,password_hash=? WHERE id=?')->execute([$hash,$hash,$uid]);log_activity($pdo,$uid,'password_changed');$msg='Password updated.';}}
}
$sessions=[];try{$s=$pdo->prepare('SELECT id,ip_address,user_agent,last_seen_at,expires_at,session_token_hash FROM user_sessions WHERE user_id=? AND revoked_at IS NULL AND expires_at>NOW() ORDER BY last_seen_at DESC');$s->execute([$uid]);$sessions=$s->fetchAll(PDO::FETCH_ASSOC);}catch(Throwable $e){}
$current=hash('sha256',session_id());
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Security | Beyond ID</title><link rel="stylesheet" href="../assets/css/admin-v2.css?v=2.1.4"><style>label{display:block;margin:14px 0 7px}input{width:100%;padding:14px;border:1px solid var(--border);border-radius:12px;background:#0d0d18;color:#fff}.session{display:flex;justify-content:space-between;gap:15px;padding:16px 0;border-bottom:1px solid var(--border)}@media(max-width:600px){.session{flex-direction:column}}</style></head><body><main class="content" style="max-width:900px;margin:auto"><p><a class="app-back" href="index.php">Dashboard</a></p><?php if($msg):?><p class="ok"><?=e($msg)?></p><?php endif;?><?php if($err):?><p class="danger"><?=e($err)?></p><?php endif;?><div class="card"><span class="badge">SECURITY</span><h1>Protect your Beyond ID</h1><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><label>New password</label><input type="password" name="password" minlength="8" required><label>Confirm password</label><input type="password" name="confirm" minlength="8" required><button name="change_password" value="1">Update password</button></form></div><div class="card" style="margin-top:16px"><h2>Active sessions</h2><?php if(!$sessions):?><p class="muted">Session registry becomes available after importing the Phase 2 migration.</p><?php endif;?><?php foreach($sessions as $s):?><div class="session"><div><strong><?=hash_equals($current,$s['session_token_hash'])?'This device':'Signed-in device'?></strong><br><small class="muted"><?=e(substr($s['user_agent']??'Browser',0,100))?><br><?=e($s['ip_address']??'')?> · Last used <?=e($s['last_seen_at'])?></small></div><?php if(!hash_equals($current,$s['session_token_hash'])):?><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><button name="revoke_session" value="<?=(int)$s['id']?>">Sign out device</button></form><?php else:?><span class="badge ok">Current</span><?php endif;?></div><?php endforeach;?></div></main><script src="/assets/js/visitor-analytics.js" defer></script></body></html>
