<?php
declare(strict_types=1);
require_once __DIR__.'/../../includes/ecosystem.php';
$wallet=beyond_app_bootstrap('Beyond Wallet');
global $pdo;
$transactions=[];
try{$stmt=$pdo->prepare('SELECT t.* FROM beyond_wallet_transactions t JOIN beyond_wallets w ON w.id=t.wallet_id WHERE w.user_id=? ORDER BY t.created_at DESC LIMIT 50');$stmt->execute([(int)$_SESSION['user_id']]);$transactions=$stmt->fetchAll(PDO::FETCH_ASSOC);}catch(Throwable $e){}
$earned=0.0;$spent=0.0;
foreach($transactions as $item){$amount=(float)($item['amount']??0);if(($item['type']??'')==='credit')$earned+=abs($amount);else $spent+=abs($amount);}
$balance=(float)($wallet['balance']??0);
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#171025"><title>Beyond Wallet | Beyond OS 2.2.1</title><link rel="stylesheet" href="../assets/css/admin-v2.css?v=2.3.1"><style>
.wallet-page{max-width:1180px;margin:auto}.wallet-hero{position:relative;overflow:hidden;display:grid;grid-template-columns:minmax(0,1.2fr) minmax(260px,.8fr);gap:28px;align-items:end;padding:clamp(28px,5vw,54px);background:radial-gradient(circle at 86% 12%,#fd5e9b55,transparent 32%),linear-gradient(135deg,#28205d,#762678 58%,#bd326f);color:#fff}.wallet-hero:after{position:absolute;right:-80px;bottom:-120px;width:330px;height:330px;border:1px solid #ffffff22;border-radius:50%;content:""}.wallet-balance h1{font-size:clamp(52px,8vw,86px);margin:12px 0 7px;letter-spacing:-.065em;line-height:.9}.wallet-balance p{max-width:560px;margin:18px 0 0;color:#f1deee}.balance-mark{font-size:clamp(62px,8vw,102px);font-weight:950;text-align:right;opacity:.28;letter-spacing:-.08em}.metric-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px;margin-top:16px}.metric{padding:20px;border:1px solid var(--border);border-radius:18px;background:var(--panel);box-shadow:var(--shadow-soft)}.metric small{display:block;color:var(--muted);font-weight:800;text-transform:uppercase;letter-spacing:.09em}.metric strong{display:block;margin-top:9px;font-size:clamp(21px,3vw,30px)}.market-layout{display:grid;grid-template-columns:minmax(0,1.45fr) minmax(270px,.55fr);gap:16px;margin-top:16px}.market-card{min-width:0}.market-head{display:flex;align-items:flex-start;justify-content:space-between;gap:18px}.market-title{display:flex;align-items:center;gap:12px}.btc-mark{display:grid;width:45px;height:45px;place-items:center;border-radius:50%;background:#f7931a;color:#fff;font-size:24px;font-weight:900}.market-price{font-size:clamp(30px,4vw,46px);font-weight:900;letter-spacing:-.045em}.market-sub{color:var(--muted)}.change{display:inline-flex;margin-top:6px;padding:5px 9px;border-radius:999px;font-size:12px;font-weight:850}.change.up{background:var(--good-soft);color:var(--good)}.change.down{background:var(--bad-soft);color:var(--bad)}.chart-wrap{position:relative;height:270px;margin-top:22px}.chart-wrap canvas{width:100%;height:100%}.chart-status{position:absolute;inset:0;display:grid;place-items:center;color:var(--muted)}.chart-status[hidden]{display:none}.compare{display:grid;gap:12px}.compare-row{padding:17px;border:1px solid var(--border);border-radius:16px;background:var(--panel2)}.compare-row span,.compare-row strong{display:block}.compare-row span{color:var(--muted);font-size:12px}.compare-row strong{margin-top:5px;font-size:20px}.disclaimer{padding:14px;border-radius:14px;background:var(--accent-soft);color:var(--muted);font-size:12px;line-height:1.5}.activity-card{margin-top:16px}.receipt{display:flex;justify-content:space-between;gap:12px;padding:15px 0;border-bottom:1px solid var(--border)}.receipt:last-child{border-bottom:0}.empty-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:18px}.source-note{margin:10px 0 0;color:var(--muted);font-size:11px}
@media(max-width:850px){.wallet-hero,.market-layout{grid-template-columns:1fr}.balance-mark{text-align:left}.metric-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:560px){.content{padding:16px}.wallet-hero{padding:25px 20px}.metric-grid{grid-template-columns:1fr 1fr}.metric{padding:16px}.receipt{align-items:flex-start;flex-direction:column}.market-head{flex-direction:column}.chart-wrap{height:220px}}
</style></head><body><main class="content wallet-page">
<section class="card wallet-hero"><div class="wallet-balance"><span class="badge">BEYOND BITS</span><h1><?=number_format($balance,0)?> <?=e((string)($wallet['currency']??'BITS'))?></h1><p>Your reward balance follows your Beyond ID across every connected app.</p></div><div class="balance-mark">bit$</div></section>
<section class="metric-grid" aria-label="Wallet summary"><article class="metric"><small>Available</small><strong><?=number_format($balance,0)?> bit$</strong></article><article class="metric"><small>Lifetime earned</small><strong><?=number_format($earned,0)?> bit$</strong></article><article class="metric"><small>Lifetime spent</small><strong><?=number_format($spent,0)?> bit$</strong></article><article class="metric"><small>Transactions</small><strong><?=count($transactions)?></strong></article></section>
<section class="market-layout"><article class="card market-card"><div class="market-head"><div class="market-title"><span class="btc-mark">₿</span><div><strong>Bitcoin market</strong><div class="market-sub">Live reference price · 7-day movement</div></div></div><div><div class="market-price" id="btcUsd">Loading…</div><div id="btcChange" class="change">Connecting</div></div></div><div class="chart-wrap"><canvas id="btcChart" aria-label="Bitcoin seven-day USD price chart" role="img"></canvas><div class="chart-status" id="chartStatus">Loading market chart…</div></div><p class="source-note">Market data: CoinGecko · refreshes every 60 seconds</p></article>
<aside class="card compare"><div><span class="badge">COMPARISON</span><h2>BTC and bit$</h2></div><div class="compare-row"><span>Bitcoin price</span><strong id="btcCad">— CAD</strong></div><div class="compare-row"><span>Your Beyond balance</span><strong><?=number_format($balance,0)?> bit$</strong></div><div class="compare-row"><span>Bitcoin 24-hour move</span><strong id="btcMove">—</strong></div><p class="disclaimer">bit$ are ecosystem rewards. They are not Bitcoin, cryptocurrency, legal tender, or directly exchangeable for BTC or cash.</p></aside></section>
<section class="card activity-card"><div class="card-heading"><h2>Wallet activity</h2><span class="badge"><?=count($transactions)?> entries</span></div><?php if(!$transactions):?><p class="muted">No wallet activity yet. Complete your profile to earn your first 100 bit$.</p><div class="empty-actions"><a class="btn" href="profile.php">Complete profile</a><a class="btn btn-secondary" href="/app-store/">Explore earning apps</a></div><?php endif;?><?php foreach($transactions as $item):?><div class="receipt"><span><?=e((string)($item['description']?:$item['app_slug']))?><br><small class="muted"><?=e((string)$item['created_at'])?></small></span><strong><?=$item['type']==='credit'?'+':'−'?><?=number_format(abs((float)$item['amount']),0)?> bit$</strong></div><?php endforeach;?></section>
</main><script>
(()=>{const usd=document.getElementById('btcUsd'),cad=document.getElementById('btcCad'),change=document.getElementById('btcChange'),move=document.getElementById('btcMove'),canvas=document.getElementById('btcChart'),status=document.getElementById('chartStatus');let points=[];const money=(n,c)=>new Intl.NumberFormat('en-CA',{style:'currency',currency:c,maximumFractionDigits:0}).format(n);function draw(){const dpr=devicePixelRatio||1,w=canvas.clientWidth,h=canvas.clientHeight;canvas.width=w*dpr;canvas.height=h*dpr;const c=canvas.getContext('2d');c.scale(dpr,dpr);c.clearRect(0,0,w,h);if(points.length<2)return;const vals=points.map(p=>p[1]),min=Math.min(...vals),max=Math.max(...vals),pad=16,range=max-min||1;c.beginPath();points.forEach((p,i)=>{const x=pad+i*(w-pad*2)/(points.length-1),y=h-pad-(p[1]-min)*(h-pad*2)/range;i?c.lineTo(x,y):c.moveTo(x,y)});const g=c.createLinearGradient(0,0,w,0);g.addColorStop(0,'#7659ef');g.addColorStop(1,'#f04f9c');c.strokeStyle=g;c.lineWidth=3;c.stroke();c.lineTo(w-pad,h-pad);c.lineTo(pad,h-pad);c.closePath();const fill=c.createLinearGradient(0,0,0,h);fill.addColorStop(0,'rgba(118,89,239,.28)');fill.addColorStop(1,'rgba(118,89,239,0)');c.fillStyle=fill;c.fill()}async function load(){try{const [p,h]=await Promise.all([fetch('https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=usd,cad&include_24hr_change=true',{cache:'no-store'}),fetch('https://api.coingecko.com/api/v3/coins/bitcoin/market_chart?vs_currency=usd&days=7',{cache:'no-store'})]);if(!p.ok||!h.ok)throw Error('Market feed unavailable');const price=(await p.json()).bitcoin,history=await h.json();points=history.prices||[];usd.textContent=money(price.usd,'USD');cad.textContent=money(price.cad,'CAD');const n=Number(price.usd_24h_change||0),label=(n>=0?'+':'')+n.toFixed(2)+'%';change.textContent=label+' today';move.textContent=label;change.className='change '+(n>=0?'up':'down');status.hidden=true;draw()}catch(e){usd.textContent='Unavailable';change.textContent='Try again soon';change.className='change';status.textContent='Live market data is temporarily unavailable.'}}load();setInterval(load,60000);addEventListener('resize',draw)})();
</script></body></html>
