ALTER TABLE profiles
    ADD COLUMN IF NOT EXISTS phone VARCHAR(50) DEFAULT NULL AFTER display_name,
    ADD COLUMN IF NOT EXISTS birthdate DATE DEFAULT NULL AFTER phone,
    ADD COLUMN IF NOT EXISTS address_line1 VARCHAR(190) DEFAULT NULL AFTER birthdate,
    ADD COLUMN IF NOT EXISTS address_line2 VARCHAR(190) DEFAULT NULL AFTER address_line1,
    ADD COLUMN IF NOT EXISTS province VARCHAR(100) DEFAULT NULL AFTER country,
    ADD COLUMN IF NOT EXISTS postal_code VARCHAR(30) DEFAULT NULL AFTER city;
