-- DailyBreath spiritual practices — SQLite 3
PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS breathing_exercises (id INTEGER PRIMARY KEY AUTOINCREMENT, slug TEXT NOT NULL, locale TEXT NOT NULL DEFAULT 'en', title TEXT NOT NULL, scripture_reference TEXT NULL, inhale_seconds INTEGER NOT NULL DEFAULT 4, hold_seconds INTEGER NOT NULL DEFAULT 0, exhale_seconds INTEGER NOT NULL DEFAULT 6, cycles INTEGER NOT NULL DEFAULT 8, prompt_text TEXT NULL, is_published INTEGER NOT NULL DEFAULT 1 CHECK(is_published IN(0,1)), sort_order INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(slug,locale));
CREATE TABLE IF NOT EXISTS breathing_sessions (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, exercise_id INTEGER NOT NULL, completed_cycles INTEGER NOT NULL DEFAULT 0, duration_seconds INTEGER NOT NULL DEFAULT 0, completed_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(exercise_id) REFERENCES breathing_exercises(id) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS idx_breathing_user_date ON breathing_sessions(user_id,completed_at);
CREATE TABLE IF NOT EXISTS guided_prayers (id INTEGER PRIMARY KEY AUTOINCREMENT, slug TEXT NOT NULL, locale TEXT NOT NULL DEFAULT 'en', category TEXT NOT NULL, title TEXT NOT NULL, prayer_text TEXT NOT NULL, scripture_reference TEXT NULL, audio_url TEXT NULL, is_published INTEGER NOT NULL DEFAULT 1 CHECK(is_published IN(0,1)), sort_order INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(slug,locale));
CREATE INDEX IF NOT EXISTS idx_prayer_category ON guided_prayers(locale,category,is_published);
CREATE TABLE IF NOT EXISTS reflection_prompts (id INTEGER PRIMARY KEY AUTOINCREMENT, slug TEXT NOT NULL, locale TEXT NOT NULL DEFAULT 'en', prompt_text TEXT NOT NULL, scripture_reference TEXT NULL, prompt_date TEXT NULL, is_published INTEGER NOT NULL DEFAULT 1 CHECK(is_published IN(0,1)), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(slug,locale));
CREATE TABLE IF NOT EXISTS reflection_journal_entries (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, prompt_id INTEGER NULL, content_ciphertext TEXT NOT NULL, encryption_version INTEGER NOT NULL DEFAULT 1, mood TEXT NULL, entry_date TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(prompt_id) REFERENCES reflection_prompts(id) ON DELETE SET NULL);
CREATE INDEX IF NOT EXISTS idx_reflection_user_date ON reflection_journal_entries(user_id,entry_date);
CREATE TABLE IF NOT EXISTS weekly_challenges (id INTEGER PRIMARY KEY AUTOINCREMENT, slug TEXT NOT NULL, locale TEXT NOT NULL DEFAULT 'en', title TEXT NOT NULL, description TEXT NOT NULL, scripture_reference TEXT NULL, starts_on TEXT NOT NULL, ends_on TEXT NOT NULL, target_count INTEGER NOT NULL DEFAULT 7, is_published INTEGER NOT NULL DEFAULT 1 CHECK(is_published IN(0,1)), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(slug,locale));
CREATE INDEX IF NOT EXISTS idx_challenge_dates ON weekly_challenges(locale,is_published,starts_on,ends_on);
CREATE TABLE IF NOT EXISTS weekly_challenge_progress (user_id INTEGER NOT NULL, challenge_id INTEGER NOT NULL, completed_count INTEGER NOT NULL DEFAULT 0, completed_at TEXT NULL, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(user_id,challenge_id), FOREIGN KEY(challenge_id) REFERENCES weekly_challenges(id) ON DELETE CASCADE);

INSERT INTO breathing_exercises(slug,locale,title,scripture_reference,inhale_seconds,hold_seconds,exhale_seconds,cycles,prompt_text,sort_order) VALUES('peace-breath','en','Peace Breath','Psalm 46:10',4,0,6,8,'Breathe in: Be still. Breathe out: Know that God is near.',10) ON CONFLICT(slug,locale) DO UPDATE SET title=excluded.title,scripture_reference=excluded.scripture_reference,inhale_seconds=excluded.inhale_seconds,hold_seconds=excluded.hold_seconds,exhale_seconds=excluded.exhale_seconds,cycles=excluded.cycles,prompt_text=excluded.prompt_text,is_published=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO guided_prayers(slug,locale,category,title,prayer_text,scripture_reference,sort_order) VALUES
('prayer-for-guidance','en','guidance','A Prayer for Guidance','God, quiet the noise around me and help me recognize the next faithful step. Give me wisdom, patience, and courage to follow where You lead.','Proverbs 3:5–6',10),
('prayer-for-peace','en','anxiety','A Prayer for Peace','God, meet me in this anxious moment. Steady my breathing, settle my thoughts, and remind me that I am not alone.','Philippians 4:6–7',20),
('prayer-for-family','en','family','A Prayer for Family','God, protect and strengthen my family. Help us speak with kindness, forgive freely, and care for one another with patience.','Colossians 3:13–14',30),
('prayer-of-gratitude','en','gratitude','A Prayer of Gratitude','God, open my eyes to the gifts already surrounding me. Let gratitude shape my words, choices, and relationships today.','1 Thessalonians 5:18',40)
ON CONFLICT(slug,locale) DO UPDATE SET category=excluded.category,title=excluded.title,prayer_text=excluded.prayer_text,scripture_reference=excluded.scripture_reference,sort_order=excluded.sort_order,is_published=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO reflection_prompts(slug,locale,prompt_text,scripture_reference,prompt_date) VALUES('where-do-you-need-stillness','en','Where do you need to choose stillness and trust today?','Psalm 46:10',CURRENT_DATE) ON CONFLICT(slug,locale) DO UPDATE SET prompt_text=excluded.prompt_text,scripture_reference=excluded.scripture_reference,prompt_date=excluded.prompt_date,is_published=1,updated_at=CURRENT_TIMESTAMP;
INSERT INTO weekly_challenges(slug,locale,title,description,scripture_reference,starts_on,ends_on,target_count) VALUES('seven-days-of-gratitude','en','Seven Days of Gratitude','Write down one specific gift each day and thank someone who made a difference in your life.','1 Thessalonians 5:18',CURRENT_DATE,DATE(CURRENT_DATE,'+6 days'),7) ON CONFLICT(slug,locale) DO UPDATE SET title=excluded.title,description=excluded.description,scripture_reference=excluded.scripture_reference,starts_on=excluded.starts_on,ends_on=excluded.ends_on,target_count=excluded.target_count,is_published=1,updated_at=CURRENT_TIMESTAMP;

