<?php
declare(strict_types=1);
require_once __DIR__ . '/../includes/ecosystem.php';
$wallet = beyond_nav_bootstrap('Beyond Baby Names');
$names = [
 ['name'=>'Amara','gender'=>'Girl','origin'=>'Igbo','meaning'=>'Grace'],
 ['name'=>'Ari','gender'=>'Unisex','origin'=>'Hebrew','meaning'=>'Lion'],
 ['name'=>'Aurora','gender'=>'Girl','origin'=>'Latin','meaning'=>'Dawn'],
 ['name'=>'Caleb','gender'=>'Boy','origin'=>'Hebrew','meaning'=>'Faithful'],
 ['name'=>'Céleste','gender'=>'Girl','origin'=>'French','meaning'=>'Heavenly'],
 ['name'=>'Elio','gender'=>'Boy','origin'=>'Italian','meaning'=>'Sun'],
 ['name'=>'Élodie','gender'=>'Girl','origin'=>'French','meaning'=>'Foreign riches'],
 ['name'=>'Ezra','gender'=>'Boy','origin'=>'Hebrew','meaning'=>'Helper'],
 ['name'=>'Imani','gender'=>'Unisex','origin'=>'Swahili','meaning'=>'Faith'],
 ['name'=>'Isla','gender'=>'Girl','origin'=>'Scottish','meaning'=>'Island'],
 ['name'=>'Jude','gender'=>'Unisex','origin'=>'Latin','meaning'=>'Praised'],
 ['name'=>'Kai','gender'=>'Unisex','origin'=>'Hawaiian','meaning'=>'Sea'],
 ['name'=>'Levi','gender'=>'Boy','origin'=>'Hebrew','meaning'=>'Joined'],
 ['name'=>'Lina','gender'=>'Girl','origin'=>'Arabic','meaning'=>'Tender'],
 ['name'=>'Luca','gender'=>'Boy','origin'=>'Italian','meaning'=>'Bringer of light'],
 ['name'=>'Maëlle','gender'=>'Girl','origin'=>'Breton','meaning'=>'Princess'],
 ['name'=>'Malia','gender'=>'Girl','origin'=>'Hawaiian','meaning'=>'Beloved'],
 ['name'=>'Mika','gender'=>'Unisex','origin'=>'Japanese','meaning'=>'Beautiful fragrance'],
 ['name'=>'Nadia','gender'=>'Girl','origin'=>'Slavic','meaning'=>'Hope'],
 ['name'=>'Noah','gender'=>'Unisex','origin'=>'Hebrew','meaning'=>'Rest'],
 ['name'=>'Sacha','gender'=>'Unisex','origin'=>'French','meaning'=>'Defender'],
 ['name'=>'Sol','gender'=>'Unisex','origin'=>'Spanish','meaning'=>'Sun'],
 ['name'=>'Théo','gender'=>'Boy','origin'=>'Greek','meaning'=>'Gift of God'],
 ['name'=>'Zuri','gender'=>'Girl','origin'=>'Swahili','meaning'=>'Beautiful'],
];
$origins = array_values(array_unique(array_column($names, 'origin'))); sort($origins);
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#3a173f"><title>Beyond Baby Names | Find a meaningful name</title><meta name="description" content="Explore baby names by meaning, origin and style, then build a private shortlist."><style>
:root{color-scheme:dark;--bg:#170d22;--panel:#2b1738;--line:#ffffff1f;--text:#fff8fb;--muted:#d9bfce;--pink:#ff74ae;--violet:#9c7cff;--gold:#ffc96b}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 85% 0,#6c275d88,transparent 32%),radial-gradient(circle at 8% 28%,#674ac744,transparent 30%),var(--bg);color:var(--text);font:500 16px/1.5 Inter,system-ui,sans-serif}.baby-shell{width:min(1180px,calc(100% - 28px));margin:auto;padding:34px 0 70px}.hero{padding:clamp(28px,7vw,76px);border:1px solid var(--line);border-radius:30px;background:linear-gradient(135deg,#55204cdd,#2a1a55dd);box-shadow:0 30px 80px #0005;overflow:hidden}.kicker{font-size:.75rem;font-weight:900;letter-spacing:.16em;color:#ffd0e4}.hero h1{max-width:800px;margin:12px 0;font-size:clamp(3rem,8vw,6.8rem);line-height:.88;letter-spacing:-.07em}.hero p{max-width:660px;color:#f2dce8;font-size:1.12rem}.actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:24px}.button,button,select,input{font:inherit}.button,button{border:1px solid var(--line);border-radius:999px;padding:12px 17px;background:#ffffff12;color:#fff;font-weight:850;cursor:pointer}.primary{border:0;background:linear-gradient(135deg,var(--pink),var(--violet));color:#180c21}.studio{margin-top:24px;padding:22px;border:1px solid var(--line);border-radius:24px;background:#21122dcc}.filters{display:grid;grid-template-columns:minmax(220px,1fr) repeat(2,minmax(150px,.32fr));gap:10px}.filters input,.filters select{width:100%;min-height:48px;padding:0 14px;border:1px solid var(--line);border-radius:13px;background:#120b1b;color:#fff}.summary{display:flex;justify-content:space-between;gap:16px;align-items:center;margin:22px 0 12px}.summary h2{margin:0}.summary span{color:var(--muted)}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px}.card{position:relative;min-height:185px;padding:21px;border:1px solid var(--line);border-radius:20px;background:linear-gradient(145deg,#3b2149,#25152f);box-shadow:0 14px 34px #0003}.card h3{margin:15px 0 4px;font-size:2rem;letter-spacing:-.04em}.card p{margin:0;color:var(--muted)}.meta{font-size:.72rem;font-weight:900;letter-spacing:.1em;color:#d6c7ff}.heart{position:absolute;right:14px;top:14px;width:42px;height:42px;padding:0;border-radius:50%;font-size:1.2rem}.heart.saved{background:var(--pink);color:#321026}.empty{grid-column:1/-1;padding:50px;text-align:center;color:var(--muted)}.shortlist{margin-top:24px;padding:22px;border:1px solid var(--line);border-radius:24px;background:#ffffff09}.chips{display:flex;flex-wrap:wrap;gap:8px}.chip{display:inline-flex;align-items:center;gap:8px;padding:9px 12px;border-radius:999px;background:#ffffff12}.chip button{padding:0;border:0;background:none;color:#ffb2d1}@media(max-width:780px){.filters,.grid{grid-template-columns:1fr}.hero{padding:34px 22px;border-radius:22px}.baby-shell{width:min(100% - 18px,1180px)}}
</style></head><body><?=beyond_shell_markup('Beyond Baby Names',$wallet)?><main class="baby-shell"><section class="hero"><span class="kicker">BEYOND BABY NAMES</span><h1>A name with a story.</h1><p>Explore names across cultures, discover their meanings, and keep a private shortlist for the names that feel right.</p><div class="actions"><button class="primary" type="button" id="surprise">Surprise me</button><a class="button" href="#discover">Browse names</a></div></section><section class="studio" id="discover"><div class="filters"><input id="search" type="search" placeholder="Search names or meanings…" aria-label="Search names"><select id="gender" aria-label="Filter by gender"><option value="">All styles</option><option>Girl</option><option>Boy</option><option>Unisex</option></select><select id="origin" aria-label="Filter by origin"><option value="">All origins</option><?php foreach($origins as $origin):?><option><?=htmlspecialchars($origin)?></option><?php endforeach;?></select></div><div class="summary"><h2>Discover names</h2><span id="count"></span></div><div class="grid" id="grid"></div></section><section class="shortlist"><div class="summary"><h2>Your shortlist</h2><span>Saved on this device</span></div><div class="chips" id="shortlist"></div></section></main><script>
const names=<?=json_encode($names,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)?>,grid=document.getElementById('grid'),search=document.getElementById('search'),gender=document.getElementById('gender'),origin=document.getElementById('origin'),count=document.getElementById('count'),shortlist=document.getElementById('shortlist');let saved=new Set(JSON.parse(localStorage.getItem('beyond-baby-names-shortlist')||'[]'));function persist(){localStorage.setItem('beyond-baby-names-shortlist',JSON.stringify([...saved]));renderShortlist()}function toggle(name){saved.has(name)?saved.delete(name):saved.add(name);persist();render()}function filtered(){const q=search.value.trim().toLocaleLowerCase();return names.filter(n=>(!q||`${n.name} ${n.meaning} ${n.origin}`.toLocaleLowerCase().includes(q))&&(!gender.value||n.gender===gender.value)&&(!origin.value||n.origin===origin.value))}function render(){const list=filtered();count.textContent=`${list.length} name${list.length===1?'':'s'}`;grid.innerHTML=list.length?list.map(n=>`<article class="card"><span class="meta">${n.origin.toUpperCase()} · ${n.gender.toUpperCase()}</span><button class="heart ${saved.has(n.name)?'saved':''}" type="button" aria-label="${saved.has(n.name)?'Remove':'Save'} ${n.name}" data-save="${n.name}">${saved.has(n.name)?'♥':'♡'}</button><h3>${n.name}</h3><p>${n.meaning}</p></article>`).join(''):'<div class="empty">No names match those filters.</div>';grid.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>toggle(b.dataset.save))}function renderShortlist(){const chosen=names.filter(n=>saved.has(n.name));shortlist.innerHTML=chosen.length?chosen.map(n=>`<span class="chip"><strong>${n.name}</strong> · ${n.meaning}<button type="button" data-remove="${n.name}" aria-label="Remove ${n.name}">×</button></span>`).join(''):'<span>No saved names yet. Tap ♡ to begin.</span>';shortlist.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>toggle(b.dataset.remove))}[search,gender,origin].forEach(el=>el.addEventListener('input',render));document.getElementById('surprise').onclick=()=>{search.value='';gender.value='';origin.value='';render();const cards=grid.querySelectorAll('.card');cards[Math.floor(Math.random()*cards.length)]?.scrollIntoView({behavior:'smooth',block:'center'})};render();renderShortlist();
</script><script src="/assets/js/visitor-analytics.js" defer></script></body></html>
